# -*- coding: utf-8 -*-
"""One NumPy snippet per reference entry, keyed by card id.

Every snippet is executed at build time and the result shown beside it is what
it produced. A snippet that raises is reported by the build, not shipped.

TWO RULES, both enforced by _build/vocabcheck.py:

1. NumPy, always. Never a pure-Python loop over data. Every lab, assignment and
   from-scratch file in the specialization is NumPy, and writing a sum as a for
   loop would model the exact habit Course 1 argues against for a week.

2. Nothing the Foundations Python track does not teach. No lambda, no list
   comprehensions, no ternary expressions, no np.c_ / meshgrid / eye / newaxis,
   no float() or int() casts added just to tidy the printed value. A reader who
   has finished F0 W2 must be able to read every line here without looking
   anything up. That is the whole point of the snippets.

Keep them SHORT — three lines is a lot.
"""

CODE = {
# ------------------------------------------------------- Foundations
"f0-function": "def f(x):\n    return 3*x - 4\nf(0), f(2), f(-1)",
"f0-superscripts": "X = np.array([[10., 2], [20, 3], [30, 4]])\nX[1], X[1, 0]        # example 2, then its first feature",
"f0-slope": "(19 - 7) / (5 - 1)      # rise over run",
"f0-derivative": "w, eps = 3.0, 1e-6\n((w+eps)**2 - (w-eps)**2) / (2*eps)     # d/dw of w**2 at w=3",
"f0-partial": "w, b, eps = 2.0, 5.0, 1e-6\ndef f(w, b):\n    return w**2*b + 3*b\n((f(w+eps,b)-f(w-eps,b))/(2*eps), (f(w,b+eps)-f(w,b-eps))/(2*eps))",
"f0-sigma": "x = np.array([4., 1, 6, 9])\nnp.sum((x - 5)**2)",
"f0-pi": "p = np.array([0.9, 0.8, 0.7])\nnp.prod(p), np.exp(np.sum(np.log(p)))   # same, but logs do not underflow",
"f0-vector-length": "np.linalg.norm([3., 4])",
"f0-dot": "a, b = np.array([2., 0, 3]), np.array([1., 5, -2])\na @ b, np.sum(a*b)      # same number, two ways",
"f0-shape-rule": "A, B = np.zeros((2, 3)), np.zeros((3, 4))\n(A @ B).shape          # inner 3s cancel, outer 2 and 4 remain",
"f0-transpose": "X = np.array([[1., 2, 3], [4, 5, 6]])\nX.T.shape, X.T",
"f0-exp": "np.round(np.exp([0., 1, -1]), 4)",
"f0-log": "np.round(np.log([1., 0.5, 0.01]), 4)     # log(1)=0, and it plunges near 0",
"f0-prob-rules": "p_spam = 0.8\n1 - p_spam, p_spam * p_spam        # complement, then two independent",
"f0-variance": "x = np.array([2., 4, 4, 4, 5, 5, 7, 9])\nx.mean(), x.var(), x.std()",
"f0-normal": "mu, sigma = 70., 10\n(85 - mu) / sigma      # the z-score: 1.5 standard deviations out",
"f0-argmax": "p = np.array([0.1, 0.6, 0.05, 0.25])\np.max(), p.argmax()     # confidence, then the prediction",
"f0-list-vs-array": "([1, 2, 3] * 2, (np.array([1, 2, 3]) * 2).tolist())",
"f0-slicing": "x = np.array([10, 20, 30, 40, 50])\nx[1:4], x[:2], x[::2]",
"f0-axis": "X = np.array([[1., 2, 3], [4, 5, 6]])\nX.sum(), X.sum(axis=0), X.sum(axis=1)",
"f0-broadcast": "A = np.array([[1., 2, 3], [4, 5, 6]])\nA + np.array([10., 20, 30])      # the row is stretched down",
"f0-star-vs-at": "w, x = np.array([1., 2, 3]), np.array([4., 5, 6])\nw * x, w @ x        # one keeps the shape, one collapses it",
"f0-mask": "y = np.array([0.2, 0.9, 0.5, 0.7])\n(y > 0.5).astype(int), (y > 0.5).sum()",
"f0-reshape": "x = np.arange(6)\nx.reshape(2, 3), x.reshape(-1, 1).shape",
"f0-pandas-five": "df = pd.DataFrame({'size': [850., 1200, 1500], 'price': [200., 310, 400]})\ndf.shape, df.isna().sum().sum(), df['price'].describe()['mean']",
"f0-to-numpy": "df = pd.DataFrame({'size': [850., 1200], 'beds': [2., 3], 'price': [200., 310]})\nX = df[['size', 'beds']].to_numpy()\ny = df['price'].to_numpy()\nX.shape, y.shape",
"f0-traceback": "X = np.zeros((100, 4))\nw = np.zeros(3)\nX.shape[1], w.shape[0]    # 4 and 3 do not match -> ValueError",
"f0-five-errors": "X = np.zeros((100, 4))\nw = np.zeros(X.shape[1])    # build w FROM the data, never a typed-in 3\nw.shape",
"f0-function-read": "def predict(X, w, b):\n    return X @ w + b\npredict(np.ones((2, 3)), np.ones(3), 1.0)",
# ---------------------------------------------------------- Course 1
"c1w1-model": "w, b = 0.2, 50.0\ndef f(x):\n    return w*x + b\nf(1500)        # a 1500 sq ft house, in $1000s",
"c1w1-notation": "X = np.array([[10., 2], [20, 3], [30, 4]])\nX[1], X[1, 1]      # the 2nd example, then its 2nd feature",
"c1w1-cost": "x = np.array([1., 2, 3]); y = np.array([1., 2, 3])\nf = 0.5*x\nnp.sum((f - y)**2) / (2*len(y))",
"c1w1-cost-shape": "x = np.array([1., 2, 3])\ny = np.array([1., 2, 3])\ndef J(w):\n    return np.sum((w*x - y)**2) / (2 * len(y))\nnp.round([J(0.5), J(1.0), J(1.5)], 4)    # a bowl: lowest in the middle",
"c1w1-contour": "def J(w, b):\n    return (w - 1)**2 + b**2\nJ(1.0, 0.5), J(0.5, 0.0), J(1.5, 0.0)    # equal cost = one ring",
"c1w1-gd-update": "w, b, alpha = 3.0, 1.0, 0.1\ndw, db = 4.0, -2.0\nw - alpha*dw, b - alpha*db      # both use the OLD values",
"c1w1-gd-sign": "def J(w):\n    return (w - 2)**2\nw = 5.0; dw = 2*(w - 2)\nw, dw, w - 0.1*dw      # positive slope -> step left",
"c1w1-alpha": "def step(w, alpha):\n    return w - alpha * 2*(w - 2)\nnp.round([step(5.0, 0.01), step(5.0, 0.4), step(5.0, 1.1)], 3)",
"c1w1-alpha-debug": "hist = np.array([5.4, 0.9, 1200.0])\nhist[1:] - hist[:-1] > 0    # any True means J rose: alpha is too big",
"c1w1-derivatives": "x = np.array([1., 2]); y = np.array([2., 4]); w = b = 0.0\nerr = (w*x + b) - y\n(err @ x)/len(y), err.mean()",
"c1w1-batch": "m = 10000\n(m, 32, 1)      # batch uses all m; mini-batch 32; stochastic 1",
"c1w1-three-parts": "X = np.ones((4, 2)); y = np.ones(4); w = np.zeros(2); b = 0.0\nf = X @ w + b                       # 1. the model\nJ = np.sum((f - y)**2)/(2*len(y))   # 2. the cost\nround(J, 3)                         # 3. minimise it",
"c1w2-multi-model": "w = np.array([0.1, 4., 10, -2]); b = 80.\nx = np.array([1200., 3, 2, 20])\nx @ w + b",
"c1w2-subscripts": "X = np.array([[1., 2], [3, 4], [5, 6]])\nX[2, 1]      # 3rd example, 2nd feature",
"c1w2-dot-vs-star": "w, x = np.array([1., 2, 3]), np.array([4., 5, 6])\n(w * x).shape, np.shape(np.dot(w, x))    # (3,) then ()",
"c1w2-why-fast": "x = np.ones(1000000)\nx @ x    # one call into compiled code, not a million Python steps",
"c1w2-scaling-why": "X = np.array([[2000., 3], [1000., 2], [1500., 4]])\nX.max(0) - X.min(0)      # ranges differ ~300x, so gradients do too",
"c1w2-scaling-how": "x = np.array([300., 1000, 2000]); mu, sd = x.mean(), x.std()\n(x/x.max(), (x - mu)/(x.max()-x.min()), (x - mu)/sd)",
"c1w2-scaling-trap": "X = np.array([[300.], [2000.]]); mu, sd = X.mean(), X.std()\n(np.array([[1800.]]) - mu) / sd      # TRAINING mu and sd, never new ones",
"c1w2-convergence": "J = np.array([5.42, 0.61, 0.30, 0.29, 0.289])\nnp.round(J[1:] - J[:-1], 3)    # shrinking negatives = converging",
"c1w2-alpha-ladder": "np.array([0.001, 0.003, 0.01, 0.03, 0.1, 0.3])      # x3 each time, not +",
"c1w2-feateng": "frontage = np.array([20., 30])\ndepth = np.array([40., 30])\nfrontage * depth    # w1*f + w2*d can never make this. Hand it over",
"c1w2-polyreg": "x = np.array([1., 2, 3])\nx, x**2, x**3    # curved in x, still a straight sum of weights",
"c1w3-why-not-linreg": "z = np.array([-3., 0, 3, 40])\n(z, 1/(1 + np.exp(-z)))      # a line is unbounded; the sigmoid is not",
"c1w3-sigmoid": "def g(z):\n    return 1/(1 + np.exp(-z))\nw, b, x = 2.0, -4.0, np.array([1., 2, 3])\nnp.round(g(w*x + b), 4)",
"c1w3-sigmoid-values": "def g(z):\n    return 1/(1 + np.exp(-z))\nnp.round(g(np.array([-5., -2, 0, 2, 5])), 4)",
"c1w3-boundary": "w, b = np.array([1., 1]), -3.0\nX = np.array([[1., 1], [2., 2]])\n(X @ w + b >= 0).astype(int)      # the boundary is where z = 0",
"c1w3-why-not-sq-error": "def g(z):\n    return 1/(1 + np.exp(-z))\nw = np.linspace(-3, 3, 7)\nnp.round((g(w*1.0) - 1)**2, 3)      # squaring a sigmoid: not a clean bowl",
"c1w3-logloss": "f, y = np.array([0.9, 0.2, 0.4]), np.array([1., 0, 1])\nnp.round(-(y*np.log(f) + (1-y)*np.log(1-f)), 4)",
"c1w3-logloss-shape": "np.round(-np.log(np.array([0.9, 0.5, 0.1, 0.01])), 4)   # confident and wrong is punished hard",
"c1w3-why-log": "np.round(np.log([1.0, 0.5, 0.001]), 3)      # 0 when right, huge when wrong",
"c1w3-gd-logistic": "def g(z):\n    return 1/(1 + np.exp(-z))\nX = np.array([[1., 2], [3., 4]]); y = np.array([0., 1.])\nw = np.zeros(2); b = 0.0\nerr = g(X @ w + b) - y\n(X.T @ err)/len(y), err.mean()      # identical in form to linear regression",
"c1w3-overfit": "train = np.array([0.42, 0.08, 0.001]); test = np.array([0.44, 0.11, 0.38])\nnp.round(test - train, 3)      # the GAP is the diagnosis",
"c1w3-address-overfit": "w = np.array([3., -4, 1])\nm = 10\nnp.round([(0/(2*m))*np.sum(w**2), (2/(2*m))*np.sum(w**2), (100/(2*m))*np.sum(w**2)], 3)",
"c1w3-regcost": "w = np.array([3., -4, 1])\nlam, m = 2.0, 10\nnp.round((lam/(2*m)) * np.sum(w**2), 4)    # b is NOT in this sum",
"c1w3-weight-decay": "alpha, lam, m = 0.01, 1.0, 100\n1 - alpha*lam/m      # shrink by this every step, THEN take the gradient step",
# ---------------------------------------------------------- Course 2
"c2w1-neuron": "def g(z):\n    return 1/(1 + np.exp(-z))\nw, b, x = np.array([2., -1]), 0.5, np.array([1., 3])\nround(g(w @ x + b), 6)",
"c2w1-hidden-layer": "X = np.array([[0., 0], [0, 1], [1, 0], [1, 1]])\ny = np.array([0., 1, 1, 0])    # XOR\nw, b = np.array([1., 1]), -0.5\n(X @ w + b > 0).astype(int), y    # no straight line gets all four",
"c2w1-layer": "W = np.zeros((4, 3)); b = np.zeros(3)\nW.shape[1], b.shape[0]      # units=3 sets both",
"c2w1-params": "n, p = 4, 5\nn*p + p",
"c2w1-master-eq": "def g(z):\n    return 1/(1 + np.exp(-z))\na_prev = np.array([1., 2, 3])\nW = np.ones((3, 2)); b = np.zeros(2)\nnp.round(g(a_prev @ W + b), 4)",
"c2w1-brackets": "layers = [np.zeros((4,5)), np.zeros((5,3))]\nlayers[1].shape      # [2] means layer 2; (i) would mean example i",
"c2w1-weight-vec-len": "sizes = [4, 5, 3, 1]\nsizes[1]      # a unit in layer 3 has one weight per layer-2 unit",
"c2w1-dense-cols": "W = np.array([[1., 4], [2., 5], [3., 6]])\nW.shape, W[:, 0]      # (inputs, units); column j is unit j",
"c2w1-shapes": "(np.array([1., 2]).shape, np.array([[1., 2]]).shape)",
"c2w1-dense-code": "def g(z):\n    return 1/(1 + np.exp(-z))\ndef dense_loop(a, W, b):\n    out = np.zeros(W.shape[1])\n    for j in range(W.shape[1]):\n        out[j] = g(W[:, j] @ a + b[j])    # column j is unit j\n    return out\nnp.round(dense_loop(np.array([1., 3]), np.array([[1., -1], [1., 2]]), np.zeros(2)), 4)",
"c2w1-dense-vec": "def dense(A, W, b, g):\n    return g(A @ W + b)\ndef g(z):\n    return 1/(1 + np.exp(-z))\nnp.round(dense(np.array([[1., 3]]), np.array([[1., -1], [1., 2]]), np.zeros(2), g), 4)",
"c2w1-matmul-rule": "A, B = np.zeros((3, 4)), np.zeros((4, 2))\n(A @ B).shape",
"c2w1-dotprod": "w, x = np.array([1., 2, 3]), np.array([4., 5, 6])\n(w * x).shape, np.shape(w @ x)      # a neuron must output ONE number",
"c2w1-vectorization": "A, W = np.ones((64, 1000)), np.ones((1000, 500))\n(A @ W).shape, 64*1000*500      # one call, 32 million multiply-adds",
"c2w2-three-steps": "['Sequential([...])  -> the model',\n 'compile(loss=...)  -> the cost',\n 'fit(X, y, epochs)  -> minimise it']",
"c2w2-bce": "f, y = np.array([0.9, 0.2]), np.array([1., 0])\nloss = -(y*np.log(f) + (1-y)*np.log(1-f))\nnp.round(loss, 4), np.round(loss.mean(), 4)      # losses, then the cost",
"c2w2-relu": "z = np.array([-3., -0.1, 0, 2, 7])\nnp.maximum(0, z)",
"c2w2-dying-relu": "z = np.array([-3., -2, -1])\nnp.maximum(0, z), (z > 0).astype(float)   # output 0 AND gradient 0: stuck for good",
"c2w2-activation-choice": "['price -> relu/linear', 'spam -> sigmoid',\n '10 digits -> softmax', 'car+bus+person -> 3 sigmoids']",
"c2w2-why-nonlinear": "W1 = np.array([[1., 2], [3., 4]])\nW2 = np.array([[5.], [6.]])\nx = np.array([[1., 1]])\nx @ W1 @ W2, x @ (W1 @ W2)    # two linear layers ARE one",
"c2w2-softmax": "z = np.array([2., 1, 0, 3])\ne = np.exp(z - z.max())\nnp.round(e/e.sum(), 4)",
"c2w2-softmax-shift": "def softmax(z):\n    e = np.exp(z - z.max())\n    return e / e.sum()\nnp.round(softmax(np.array([10., 1, 1])), 4), np.round(softmax(np.array([110., 101, 101])), 4)",
"c2w2-from-logits": "z = np.array([400., 0, -400])\nlogsm = z - z.max() - np.log(np.exp(z - z.max()).sum())\nnp.round(logsm, 1)      # stable; log(softmax(z)) would give -inf",
"c2w2-multiclass-vs-label": "z = np.array([3., 2.5, -1])\nsm = np.exp(z)/np.exp(z).sum(); sig = 1/(1 + np.exp(-z))\nround(sm.sum(), 3), np.round(sig.sum(), 3)   # 1 vs anything",
"c2w2-adam": "g = np.array([1., 1, 1, -1, 1, -1])\ng[:3].sum(), g[3:].sum()    # same sign -> speed up; flipping -> slow down",
"c2w2-conv": "patch = np.ones((3, 3))\nkernel = np.ones((3, 3))\n(patch * kernel).sum(), 3*3 + 1    # one window, 10 parameters reused everywhere",
"c2w2-backprop-cost": "n_params = 1000000\nn_params + 1, 2*n_params      # backprop: one pass. Nudging each: a million",
"c2w2-chain-rule": "w, b, x, y = 3., 1., 2., 5.\na = w*x + b\ndJ_da = 2*(a - y)\ndJ_da, dJ_da*x, dJ_da*1.0      # dJ/da, dJ/dw, dJ/db",
"c2w2-mse-vs-bce": "f, y = np.array([0.01, 0.99]), np.array([1., 0])\nnp.round((f - y)**2, 4), np.round(-(y*np.log(f) + (1-y)*np.log(1-f)), 4)",
"c2w3-diagnostic": "base, jtr, jcv = 10.6, 10.8, 14.8\nround(jtr - base, 1), round(jcv - jtr, 1)      # bias gap, then variance gap",
"c2w3-three-sets": "n = 1000\nn*6//10, n*2//10, n*2//10    # train / choose / report once",
"c2w3-fix-table": "{'bias': ['more features', 'polynomials', 'decrease lambda'],\n 'variance': ['more data', 'increase lambda', 'fewer features']}",
"c2w3-more-data": "jtr = np.array([0.28, 0.29, 0.29]); jcv = np.array([0.31, 0.30, 0.30])\nnp.round(jcv - jtr, 3)      # gap already gone -> more data changes nothing",
"c2w3-baseline": "jtr = 10.8\njtr - 10.6, jtr - 0.5    # same number, opposite verdicts",
"c2w3-learning-curves": "m = np.array([100., 200, 400, 800])\njtr = np.array([0.05, 0.12, 0.19, 0.22]); jcv = np.array([0.55, 0.38, 0.28, 0.24])\nnp.round(jcv - jtr, 3)      # still shrinking -> more data will help",
"c2w3-nn-recipe": "jtr, jcv, base = 0.19, 0.20, 0.02\n(jtr - base > 0.05, jcv - jtr > 0.05)      # (bigger network?, more data?)",
"c2w3-error-analysis": "counts = np.array([21., 18, 18, 5])    # pharma, phishing, misspellings, image-only\ncounts[:2].sum(), counts[-1]    # the top two cap 39% of errors; image-only caps 5%",
"c2w3-augmentation": "img = np.array([[1., 2], [3, 4]])\nimg[:, ::-1]    # a distortion a REAL example could plausibly have",
"c2w3-transfer": "layers = ['conv1', 'conv2', 'conv3', 'output']\n(layers[:-1], layers[-1:])      # freeze the front, always replace the head",
"c2w3-precision-recall": "tp, fp, fn = 8, 22, 12\ntp/(tp+fp), tp/(tp+fn)      # of those flagged / of those that were real",
"c2w3-accuracy-trap": "y = np.zeros(1000); y[:5] = 1\n(np.zeros(1000) == y).mean()      # predicting 'no' scores 99.5%",
"c2w3-f1": "p, r = 0.267, 0.400\nround(2*p*r/(p + r), 4)",
"c2w3-threshold": "prob = np.array([0.1, 0.35, 0.6, 0.9])\n(prob >= 0.5).sum(), (prob >= 0.3).sum()   # lower it: more caught, more false alarms",
"c2w3-fairness": "acc = np.array([0.96, 0.72])\nacc.mean(), acc.min()      # overall hides the group it fails",
"c2w3-leakage": "X = np.arange(10.).reshape(-1, 1); mu = X.mean()\nround(mu, 2)      # scaling BEFORE the split leaks test data into training",
"c2w4-tree-decisions": "['which feature to split on', 'when to stop splitting']",
"c2w4-entropy": "def H(p):\n    return -p*np.log2(p) - (1-p)*np.log2(1-p)\nnp.round([H(0.5), H(0.8)], 4)    # 1.0 at 50/50; H(0) and H(1) are 0 by convention",
"c2w4-infogain": "def H(p):\n    return -p*np.log2(p) - (1-p)*np.log2(1-p)\nnp.round(H(0.5) - (0.5*H(0.8) + 0.5*H(0.2)), 4)    # the 0.5s are the easy bit to drop",
"c2w4-id-column": "def H(p):\n    return -p*np.log2(p) - (1-p)*np.log2(1-p)\nnp.round(H(0.5) - 0.0, 4)    # every leaf pure -> maximum gain, and useless",
"c2w4-continuous": "w = np.array([7.2, 8.8, 9.2, 15.0])    # sorted\n(w[:-1] + w[1:]) / 2    # try every midpoint between neighbours",
"c2w4-regtree": "leaf = np.array([7.2, 8.8, 7.6, 10.2])\nround(leaf.var(), 4), np.round(leaf.mean(), 4)   # variance replaces entropy; the leaf predicts the mean",
"c2w4-onehot": "np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])    # no invented order, no invented spacing",
"c2w4-why-ensemble": "gains = np.array([0.281, 0.278])\ngains.max() - gains.min()    # a near-tie: one example flips the root",
"c2w4-bootstrap": "m = 10\nround(1 - (1 - 1/m)**m, 4), round(1 - 1/np.e, 4)",
"c2w4-random-forest": "n = 100\nnp.sqrt(n)    # consider only this many features per node, so the trees differ",
"c2w4-boosting": "['bagging: independent samples, trees in parallel',\n 'boosting: each tree fixes the last, strictly sequential']",
"c2w4-boost-shallow": "[3, 6]      # boosting adds capacity by adding trees, not by deepening them",
"c2w4-tree-vs-nn": "{'tabular': 'trees', 'images/audio/text': 'neural network',\n 'transfer learning': 'neural network only'}",
# ---------------------------------------------------------- Course 3
"c3w1-kmeans-steps": "X = np.array([[1., 1], [1.5, 2], [3, 4], [5, 7]])\nc0, c1 = np.array([1., 1]), np.array([5., 7])\nd0 = np.sqrt(((X - c0)**2).sum(axis=1))\nd1 = np.sqrt(((X - c1)**2).sum(axis=1))\n(d0 > d1).astype(int)    # 0 = nearer the first centroid",
"c3w1-distortion": "X = np.array([[1., 1], [1.5, 2], [3, 4]])\nc = np.array([1.8333, 2.3333])\nnp.round(np.mean(((X - c)**2).sum(axis=1)), 4)",
"c3w1-init": "J = np.array([1.7778, 1.3125, 1.7778])    # three random starts\nJ.min(), J.argmin()    # keep the lowest-cost run",
"c3w1-choose-k": "J = np.array([52.1, 24.3, 11.8, 9.9, 8.7])\nnp.round(J[:-1] - J[1:], 2)    # drops collapse after k=3; J never rises",
"c3w1-gaussian": "x = np.array([3., 4, 5, 6, 7])\nmu, var = x.mean(), x.var()\np7 = np.exp(-(7 - mu)**2 / (2*var)) / np.sqrt(2*np.pi*var)\nmu, var, np.round(p7, 6)",
"c3w1-sigma-ranges": "[0.68, 0.95, 0.997]      # within 1, 2 and 3 standard deviations",
"c3w1-anomaly": "def p(v, mu, var):\n    return np.exp(-(v-mu)**2/(2*var)) / np.sqrt(2*np.pi*var)\npx = p(5., 5, 2) * p(16., 10, 4)      # independent features multiply\nround(px, 7), bool(px < 0.001)",
"c3w1-anomaly-split": "{'train': '6000 normal only', 'cv': '2000 normal + 10 faulty',\n 'test': '2000 normal + 10 faulty'}",
"c3w1-anomaly-vs-sup": "['few positives + future ones look DIFFERENT -> anomaly',\n 'many positives + future ones look the SAME -> supervised']",
"c3w1-features-anomaly": "x = np.array([0., 1, 5, 200])\nnp.round(np.log(x + 1), 4)      # log pulls a long right tail into a bell",
"c3w2-notation": "Y = np.array([[5., 5, np.nan], [np.nan, 4, 0]])\nR = (~np.isnan(Y)).astype(int)\nR      # r(i,j)=1 means rated; y(i,j) is the rating itself",
"c3w2-collab": "X = np.ones((2, 3))\nW = np.ones((2, 3))\nY = np.array([[5., 0], [0., 5]])\nR = np.ones((2, 2))\nnp.round(0.5 * np.sum((((X @ W.T) - Y) * R)**2), 4)",
"c3w2-collab-init": "X = np.zeros((2, 3)); W = np.zeros((2, 3))\nX @ W.T      # all-zero stays all-zero: every gradient is 0. Use small randoms",
"c3w2-meannorm": "Y = np.array([5., 5, 0, 0])    # one film, four users\nmu = Y.mean()\nmu, Y - mu    # a new user is predicted mu, not 0",
"c3w2-R-mask": "err = np.array([[2., 3], [1., 4]]); R = np.array([[1, 0], [1, 1]])\nerr * R      # the unrated cell is switched off, not treated as 0",
"c3w2-related": "xa = np.array([0.9, 0.1, 0.5])\ncands = np.array([[0.8, 0.2, 0.5], [0.1, 0.9, 0.5], [0.9, 0.1, 0.9]])\nd = ((cands - xa)**2).sum(axis=1)\nnp.round(d, 3), d.argmin()",
"c3w2-cf-vs-cbf": "['collaborative: learns x from ratings, cold-starts badly',\n 'content-based: given features, handles a brand-new item']",
"c3w2-two-tower": "vu, vm = np.ones(32), np.ones(32)\nvu.shape == vm.shape, vu @ vm      # same length, or the dot product is undefined",
"c3w2-retrieval": "catalogue, shortlist = 10000000, 300\ncatalogue // shortlist      # retrieve cheaply, then rank the few",
"c3w2-ethics": "['it decides what people SEE, not just what they get',\n 'engagement is not the same as benefit']",
"c3w2-l2norm": "v = np.array([3., 4])\nu = v / np.linalg.norm(v)\nnp.round(u, 4), np.round(np.linalg.norm(u), 6)   # length 1, so a dot product IS the cosine",
"c3w2-pca": "X = np.array([[1., 2], [2, 1], [3, 5], [4, 4], [5, 3]])\nXc = X - X.mean(axis=0)\n(Xc.T @ Xc) / len(Xc)    # the covariance matrix; PCA takes its eigenvectors",
"c3w2-pca-use": "['visualisation: still good', 'compression: storage is cheap now',\n 'speed-up/overfitting: use regularisation instead']",
"c3w3-rl-vs-sup": "['no correct action is ever given, only a reward',\n 'your own actions decide what data you see',\n 'the reward arrives long after the action']",
"c3w3-return": "g = 0.5\nrewards = np.array([0., 0, 0, 100])\nnp.round((rewards * g**np.arange(4)).sum(), 4)",
"c3w3-mdp": "['states', 'actions', 'rewards', 'gamma', 'transitions']   # Markov: only WHERE you are matters",
"c3w3-q": "g = 0.5\nV = np.array([100., 50, 25, 12.5, 20, 40])\ng*V[2], g*V[4]    # from state 4: left, then right. Left wins",
"c3w3-bellman": "g, V = 0.5, np.array([100., 50, 25, 12.5, 20, 40])\nround(max(0 + g*V[0], 0 + g*V[2]), 4)      # V(2) = R + gamma * best next",
"c3w3-rover-values": "R = np.array([100., 0, 0, 0, 0, 40])\ng = 0.5\nV = np.array([100., 0, 0, 0, 0, 40])\nfor _ in range(60):\n    V[1:5] = np.maximum(g*V[0:4], g*V[2:6])\nV",
"c3w3-stochastic": "outcomes = np.array([100., 0])\nprobs = np.array([0.9, 0.1])\noutcomes @ probs    # maximise the EXPECTED return, not the return",
"c3w3-continuous": "buckets, dims = 100, 6\nbuckets**dims      # a table would need this many cells",
"c3w3-dqn": "R, g = 0.0, 0.5\nQ_next = np.array([12.5, 10.0])\nR + g*Q_next.max()      # y = R + gamma * max Q(s', a')",
"c3w3-replay": "buffer = np.arange(10)\nbuffer[[7, 2, 9, 4]]    # a random scatter, not four in a row: breaks correlation",
"c3w3-arch": "actions = 4\n(actions, 1)      # one forward pass gives all Q values, not one each",
"c3w3-epsilon": "eps = 0.05\n1000 * eps, 1000 * (1 - eps)    # ~50 random moves, ~950 greedy ones",
"c3w3-soft-update": "tau = 0.001\ntarget, online = 10.0, 20.0\nround((1-tau)*target + tau*online, 4)      # the target barely moves, so it can be learned from",
"c3w3-reward-design": "landed = np.array([0., 0, 0, 0, 100])\nlanded[:4].sum()    # only the last step pays: nothing to learn from until then",
"c3w3-state-of-rl": "['works: simulation, games, robotics in a rig',\n 'hard: real robots, anything where a mistake is expensive']",
}
