# -*- coding: utf-8 -*-
"""C3 · Week 3 — Reinforcement learning."""
from kit import (kid, key, warn, trap, note, card, eq, eqp, decode, table, demo,
                 quiz, links, code, h2, grid2, grid3, pretest, explain)

REPO = "../../C3%20-%20Unsupervised%20Learning,%20Recommenders,%20Reinforcement%20Learning"
L = []

# ============================================================ 1
L.append(dict(
    slug="01-what-is-rl", title="What is reinforcement learning?", mins=9, tag="intuition",
    lede="The third kind of learning. Nobody tells you the right answer — you find out afterwards whether "
         "things went well.",
    body=(
        pretest("""<p>No right answers, only rewards that arrive late. <b>Guess why you cannot just use supervised learning</b> with the reward as the label.</p>""",
        """<p>Watch for the credit-assignment problem: which of the last fifty actions earned the reward?</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>How do you train a dog? You do not show it a thousand photos labelled “correct sitting
posture”. You say “sit”, and when something roughly sit-shaped happens, it gets a treat.</p>
<p>The dog never receives the right answer. It receives <b>consequences</b>, and works backwards from
them.</p>
<p>That is reinforcement learning. And the hard part is the delay: the treat arrives after the sit, but
which of the last twenty things the dog did actually earned it?</p>""")

        + h2("🎬", "Watch it move")
        + demo("whatisrl", "Agent and environment, passing things back and forth",
               "actions go out, states and rewards come back")

        + h2("🔢", "How it differs from everything so far")
        + table(["", "Supervised", "Unsupervised", "<b>Reinforcement</b>"],
                [["You are given", "(x, y) pairs", "x only", "<b>a reward signal</b>"],
                 ["Feedback is", "the exact right answer", "none", "<b>a number, often much later</b>"],
                 ["You learn", "a mapping x → y", "structure in x", "<b>a policy: state → action</b>"],
                 ["Data is", "fixed", "fixed", "<b>generated by your own actions</b>"]])
        + decode([
            ("agent", "“the decider”", "The thing choosing actions. Your program."),
            ("environment", "“the world”", "Everything else. It receives actions and returns a new state and a reward."),
            ("state <var>s</var>", "“where you are”", "Everything the agent knows about its situation right now."),
            ("action <var>a</var>", "“what you do”", "One of the available choices."),
            ("reward <var>R</var>", "“the score”", "A number the environment hands back. Positive for good, negative for bad. <b>You design it.</b>"),
            ("policy π", "“the rule”", "The thing being learned: for each state, which action to take."),
        ])
        + key("""<p>The last row of that table is the one that changes everything. In supervised learning
your dataset is fixed. In RL, <b>the agent generates its own training data by acting</b> — so a bad early
policy produces bad data, which makes learning harder, which is the core difficulty of the whole
field.</p>""")

        + h2("🚁", "Where it has genuinely worked")
        + grid3(
            card("<h3>Games</h3><p>Atari from raw pixels, Go, chess, StarCraft. Perfect simulators, "
                 "unlimited trials, clear rewards.</p>"),
            card("<h3>Control</h3><p>Andrew’s own autonomous helicopter; data-centre cooling; some robot "
                 "locomotion. Usually trained in simulation first.</p>"),
            card("<h3>RLHF</h3><p>Aligning large language models to human preference. Quietly the most "
                 "widely deployed application of RL today.</p>"))

        + explain("""<p>The successes listed are mostly simulations or tightly controlled settings. <b>Why does that pattern hold?</b></p>""",
            """<p>Because RL learns by trying things and failing many times. A simulator makes failure free and fast; the physical world makes it slow, expensive and sometimes destructive. The bottleneck is not the algorithm but the cost of an attempt.</p>""")
        + h2("✅", "Check yourself")
        + quiz([
            ("Why can't you use supervised learning to fly a helicopter?",
             "<p>Because nobody can produce the label. For a given position and velocity, what is the "
             "exactly correct control-stick position? No expert can specify it for every state — but "
             "everyone can agree that crashing is bad.</p>"),
            ("What is the credit assignment problem?",
             "<p>The reward arrives long after the actions that earned it. Which of the last hundred "
             "moves deserves the credit? Discounting and the Bellman equation are how RL answers this.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto — Reinforcement Learning: An Introduction",
             "Free PDF, and the definitive textbook. Chapters 1 and 3 cover this week's first half properly."),
            ("paper", "https://www.nature.com/articles/nature14236",
             "Mnih et al. (2015) — Human-level control through deep reinforcement learning",
             "The DQN paper. The exact algorithm you build this week, playing Atari from pixels."),
            ("play", "https://gymnasium.farama.org/",
             "Gymnasium (formerly OpenAI Gym)",
             "The standard environment library. <code>LunarLander-v2</code> is the one in the assignment."),
        ])
    )))

# ============================================================ 2
L.append(dict(
    slug="02-mars-rover", title="The Mars rover example", mins=8, tag="core",
    lede="Six squares, two actions, two rewards. Small enough to compute by hand, and every concept in the "
         "week fits inside it.",
    body=(
        pretest("""<p>Six positions, rewards at both ends, and you may step left or right. <b>Guess what makes this a good teaching example</b> despite being tiny.</p>""",
        """<p>Watch for the vocabulary being introduced on something you can hold in your head: state, action, reward, next state.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>A little rover sits on one of six squares. It can drive <b>left</b> or <b>right</b>.</p>
<p>Square 1 has a really interesting rock — worth 100 points. Square 6 has a duller rock — worth 40.
Everything in between is worth nothing.</p>
<p>Once it reaches either end it stops: the trip is over. Start it in the middle. Which way should it
go?</p>""")

        + h2("🎬", "Watch it move")
        + demo("marsrover", "Drive it yourself",
               "start at state 4 and try both directions — watch the discounted return")

        + h2("🔢", "The setup")
        + table(["Piece", "In this example"],
                [["states S", "{1, 2, 3, 4, 5, 6}"],
                 ["actions A", "{left, right}"],
                 ["rewards R(s)", "R(1) = 100, R(6) = 40, everything else 0"],
                 ["terminal states", "1 and 6 — reaching either ends the episode"],
                 ["discount γ", "0.5 in this course (unrealistically small, but the arithmetic stays readable)"]])
        + decode([
            ("terminal state", "“the end”", "The episode stops. No further actions, no further rewards."),
            ("episode", "“one attempt”", "A complete run from the starting state to a terminal state."),
            ("R(s)", "“the reward for being in state s”", "This course attaches rewards to states. Some texts attach them to (state, action) or to transitions — the maths is equivalent."),
        ])
        + key("""<p>Everything you meet this week — returns, policies, Q, the Bellman equation — will be
demonstrated on this one six-square strip. It is worth getting comfortable with it now.</p>""")

        + h2("🧮", "The question that makes it interesting")
        + """<p>From state 4: going left takes <b>3 steps</b> to reach a reward of <b>100</b>. Going right
takes <b>2 steps</b> to reach a reward of <b>40</b>.</p>
<p>Nearer but smaller, or further but bigger? You cannot answer that without a rule for trading time
against value — and that rule is the next lesson.</p>"""

        + h2("✅", "Check yourself")
        + quiz([
            ("How many states, and how many are terminal?",
             "<p>Six states; <b>two</b> are terminal (1 and 6). The rover only ever makes decisions in the "
             "four middle states.</p>"),
            ("Why does the episode end at a terminal state?",
             "<p>By definition — it is the end of one attempt. Without terminal states the return could "
             "keep accumulating forever, which is why discounting matters even more in that case.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, chapter 3",
             "The formal MDP definition. This rover is a textbook example of a finite MDP."),
            ("lab", REPO + "/week3/optional-labs/State-action%20value%20function%20example.ipynb",
             "Optional lab: state-action value function",
             "In this repo. Change the rewards and γ and watch the Q values recompute."),
        ])
    )))

# ============================================================ 3
L.append(dict(
    slug="03-the-return", title="The Return in reinforcement learning", mins=11, tag="maths",
    lede="How to compare “a lot, later” against “a little, sooner”. One Greek letter does all the work.",
    body=(
        pretest("""<p>A reward of 100 now versus 100 in ten steps. <b>Should they count equally?</b> Commit, then guess how you would express your answer as a formula.</p>""",
        """<p>Watch for γ, and for what γ near 1 versus γ near 0 does to how patient the agent becomes.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>£100 today or £100 next year? Today, obviously.</p>
<p>£100 today or £110 next year? Now it depends on how patient you are.</p>
<p>Reinforcement learning uses a number called <b>γ</b> (gamma) to settle this. Every step you wait, the
reward gets multiplied by γ. With γ = 0.5, a reward two steps away is only worth a quarter of its face
value.</p>
<p>γ near 1 = a patient agent. γ near 0 = a greedy one that grabs whatever is closest.</p>""")

        + h2("🔢", "The maths, decoded")
        + eqp([
            'Return <span class="op">=</span> <var>R</var><sub>1</sub> <span class="op">+</span> ',
            ('<var class="hl-a">γ</var>', "gamma-discount", "worth slightly less each step later"),
            '<var>R</var><sub>2</sub> <span class="op">+</span> <var class="hl-a">γ</var><sup>2</sup><var>R</var><sub>3</sub> <span class="op">+</span> <var class="hl-a">γ</var><sup>3</sup><var>R</var><sub>4</sub> <span class="op">+</span> …',
        ], "the discounted return — click γ")
        + decode([
            ("<var class='hl-a'>γ</var>", "“gamma”, the discount factor", "Between 0 and 1. How much a reward one step later is worth."),
            ("<var>R</var><sub>1</sub>", "“the first reward”", "Collected at the state you start in. Not discounted at all."),
            ("γ<sup>2</sup>", "“gamma squared”", "Two steps away, so γ has been applied twice. 0.5² = 0.25."),
            ("return", "“the total, discounted”", "The one quantity everything in RL is trying to maximise."),
        ])

        + h2("🎬", "Watch it move")
        + demo("returns", "Left versus right from state 4",
               "drag γ from 0.1 to 0.99 and watch the better choice flip")

        + h2("🧮", "The worked numbers")
        + table(["From state 4", "Path", "Return with γ = 0.5"],
                [["go <b>left</b>", "4 → 3 → 2 → 1", "0 + 0.5(0) + 0.25(0) + 0.125(100) = <b>12.5</b>"],
                 ["go <b>right</b>", "4 → 5 → 6", "0 + 0.5(0) + 0.25(40) = <b>10</b>"]])
        + """<p>So with γ = 0.5, left wins — 12.5 beats 10. But it is close. Drag γ down to about 0.4 in the
demo and right becomes better: the 100 is too far away to be worth the wait.</p>"""
        + key("""<p>γ is not a fact about the world — it is a <b>choice you make</b> about how much you care
about the future. It encodes impatience. Real systems typically use 0.9, 0.99 or 0.999; this course uses
0.5 purely so the arithmetic stays doable in your head.</p>""")

        + explain("""<p>A reward two steps away was worth 6.25 rather than 25. <b>Why discount at all, rather than counting every reward equally?</b></p>""",
            """<p>Because a distant reward is less certain and less useful, and because without discounting an endless task has an infinite return that cannot be compared with anything. γ makes the sum finite and encodes a preference for sooner.</p>""")
        + h2("🔬", "Why discount at all?")
        + """<p>Three genuine reasons, and it is worth knowing all three:</p>
<ol>
<li><b>The maths needs it.</b> In a task with no terminal state, an undiscounted sum of rewards can be
infinite, and infinity minus infinity gives you nothing to optimise. γ &lt; 1 makes the sum converge.</li>
<li><b>It models real impatience.</b> In finance this is literally the interest rate. A reward now can be
reinvested; a reward later cannot.</li>
<li><b>It handles uncertainty.</b> The further ahead you look, the less reliable your model of what will
happen. Discounting is a rough way of saying “I trust the near future more”.</li>
</ol>"""
        + note("""<p>With negative rewards, discounting has a memorable side effect: it pushes the agent to
<b>delay</b> them. A cost of −100 taken ten steps from now hurts much less than one taken immediately. An
agent that must eventually pay a penalty will procrastinate — which is sometimes exactly right, and
sometimes a bug in your reward design.</p>""", "A quirk worth knowing")

        + h2("🕳", "Traps")
        + trap("""<p><b>Discounting the first reward.</b> R₁ is multiplied by γ⁰ = 1. The exponent counts
<em>steps taken</em>, so it starts at zero.</p>""")
        + trap("""<p><b>γ = 1 in a non-episodic task.</b> The return may not converge, and the algorithm has
nothing well-defined to maximise.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Rewards 0, 0, 0, 100 over four steps with γ = 0.9. What is the return?",
             "<p>0.9³ × 100 = <b>72.9</b>. With γ = 0.5 it would be 0.125 × 100 = 12.5 — patience is worth "
             "a great deal here.</p>"),
            ("Why does γ = 0.99 make an agent more patient than γ = 0.5?",
             "<p>Because 0.99¹⁰ ≈ 0.90 while 0.5¹⁰ ≈ 0.001. Ten steps out, the patient agent still values "
             "the reward at 90% of face value; the impatient one has essentially forgotten it.</p>"),
            ("What does a large γ do to the difficulty of learning?",
             "<p>It makes it harder. The agent must credit rewards to actions far in the past, and the "
             "effective horizon it must reason over is longer.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, section 3.3",
             "Returns and episodes, including the continuing-task case where γ is mathematically essential."),
            ("paper", "https://arxiv.org/abs/1512.02011",
             "François-Lavet, Fonteneau & Ernst (2015) — How to Discount Deep Reinforcement Learning",
             "Why a smaller γ than the “true” one often learns better, and how to adapt it during training."),
        ])
    )))

# ============================================================ 4
L.append(dict(
    slug="04-policies", title="Making decisions: policies", mins=8, tag="core",
    lede="A policy is a lookup table: state in, action out. Finding the best one is the entire problem.",
    body=(
        pretest("""<p>You want a rule that says what to do in every state. <b>Guess what that object is called</b>, and what makes one such rule better than another.</p>""",
        """<p>Watch for π, which here has nothing to do with 3.14159.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>A policy is your plan for every situation, written down in advance.</p>
<p>“On square 2, go left. On square 3, go left. On square 4, go left. On square 5, go right.”</p>
<p>That is it. That is a policy. It is not a sequence of moves — it is a rule that tells you what to do
<b>wherever</b> you find yourself.</p>""")

        + h2("🎬", "Watch it move")
        + demo("policies", "Four different policies on the same rover",
               "the arrows are π(s); the green numbers are how much each state is worth under that policy")

        + h2("🔢", "The maths, decoded")
        + eq("""<var class="hl-a">π</var>(<var>s</var>) <span class="op">=</span> <var>a</var>""",
             "the policy: given state s, take action a")
        + decode([
            ("π", "“pi”, the policy", "Nothing to do with 3.14159. Just the conventional letter for a policy."),
            ("π*", "“pi star”", "The <b>optimal</b> policy — the one that maximises expected return from every state."),
            ("deterministic policy", "“always the same action”", "π(s) returns one action. What this course uses."),
            ("stochastic policy", "“a distribution over actions”", "π(a|s) gives a probability for each action. Standard in policy-gradient methods, which this course does not cover."),
            ("V(s)", "“the value of state s”", "The expected return if you start in s and follow π from then on."),
        ])
        + key("""<p>The goal, stated precisely: <b>find the policy π that maximises the expected return from
every state.</b> Remarkably, in an MDP there is always a single policy that is optimal for <em>all</em>
states simultaneously — you never have to trade one state off against another.</p>""")

        + h2("🔬", "The optimal policy here is not uniform")
        + """<p>For the rover with γ = 0.5, the optimal policy is <b>← ← ← →</b>: states 2, 3 and 4 go left
towards the 100, but state 5 goes right towards the 40.</p>
<p>That split is the interesting part. State 5 is one step from a reward of 40 and four steps from a reward
of 100, and with γ = 0.5 that distance is decisive. The dividing line sits between states 4 and 5, and
changing γ moves it.</p>"""

        + h2("🕳", "Traps")
        + trap("""<p><b>Thinking of a policy as a route.</b> It is not “go left, left, left”. It is a rule
covering every square, including ones you might never visit. That matters the moment the environment is
stochastic and you end up somewhere unplanned.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Write a policy for the rover as a table.",
             "<p>π(2) = ←, π(3) = ←, π(4) = ←, π(5) = →. States 1 and 6 are terminal, so no action is "
             "needed there.</p>"),
            ("Why does the optimal policy send state 5 right when states 2–4 go left?",
             "<p>Because state 5 is one step from 40 and four steps from 100. With γ = 0.5, 0.5×40 = 20 "
             "beats 0.5⁴×100 = 6.25.</p>"),
            ("Does an optimal policy always exist for a finite MDP?",
             "<p>Yes — and it can always be taken to be deterministic and optimal for every state at "
             "once. This is a genuine theorem, not just a convenient assumption.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, section 3.5–3.6",
             "Policies, value functions, and the proof that an optimal deterministic policy exists."),
        ])
    )))

# ============================================================ 5
L.append(dict(
    slug="05-review-of-key-concepts", title="Review of key concepts", mins=7, tag="core",
    lede="The five pieces have a collective name — Markov Decision Process — and one assumption hiding "
         "inside it.",
    body=(
        pretest("""<p>State, action, reward, discount, return, policy. <b>Say what each one is, out loud, before reading.</b> Note which one you fumble.</p>""",
        """<p>Watch for the formalism these six pieces add up to, and for the name it carries.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>Everything so far has been five pieces: where you are, what you can do, what you
get for doing it, how much you care about later, and where you end up. Those five together have a
name &mdash; a <b>Markov Decision Process</b>.</p>
<p>Hidden inside that name is one assumption worth knowing about: <b>where you are now is all that
matters</b>. How you got there is forgotten. For the rover on its line that is exactly true. For a
poker hand, or a patient, or a conversation, it is not &mdash; and the section below says what
people do about that.</p>""")

        +h2("🎬", "Watch it move")
        + demo("mdpreview", "The whole formalism on one screen",
               "states, actions, rewards, discount, policy, return")

        + h2("🔢", "The formalism")
        + table(["Symbol", "Name", "In the rover", "In the lunar lander"],
                [["S", "states", "6 squares", "8 continuous numbers"],
                 ["A", "actions", "left, right", "4 thrusters"],
                 ["R(s)", "rewards", "100, 0, 40", "+100 landing, −100 crash, −0.3 fuel"],
                 ["γ", "discount", "0.5", "0.985"],
                 ["π(s)", "policy", "the thing being learned", "the thing being learned"]])
        + decode([
            ("MDP", "“Markov Decision Process”", "The formal name for this whole setup. Almost all of RL theory is stated in these terms."),
            ("Markov", "“the past does not matter”", "The next state depends <b>only</b> on the current state and action — not on how you got here."),
            ("model", "“the transition rules”", "P(s′ | s, a). The rover’s is trivial. Deep Q-learning never learns it explicitly — it is <em>model-free</em>."),
        ])
        + key("""<p>The Markov assumption is doing real work. If your problem violates it — if what happens
next genuinely depends on history — the fix is not to abandon RL. It is to <b>put the missing history into
the state</b>. That is why Atari agents stack four consecutive frames: one frame cannot tell you which way
the ball is moving.</p>""")

        + h2("🔬", "Where Markov fails, and what people do")
        + grid2(
            card("<h3>Partial observability</h3><p>A poker player cannot see the opponent’s cards, so the "
                 "visible state is not the true state. This is a POMDP, and it is substantially harder.</p>"),
            card("<h3>The usual fix</h3><p>Add history to the state: stack recent frames, or keep a "
                 "recurrent hidden state that summarises everything seen so far.</p>"))

        + h2("✅", "Check yourself")
        + quiz([
            ("What does the Markov property claim, in one sentence?",
             "<p>That the future depends only on the current state and action, not on the path taken to "
             "reach it.</p>"),
            ("A single frame of Pong shows the ball's position but not its direction. Is that Markov?",
             "<p><b>No</b> — you cannot predict the next state from one frame. Stacking four consecutive "
             "frames restores the property, which is exactly what DQN does.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, chapter 3 — Finite Markov Decision Processes",
             "The complete formal treatment, and the source of essentially all the notation used here."),
            ("docs", "https://gymnasium.farama.org/api/env/",
             "Gymnasium — the Env interface",
             "<code>step(action) -> (observation, reward, terminated, truncated, info)</code>. The MDP, as an API."),
        ])
    )))

# ============================================================ 6
L.append(dict(
    slug="06-state-action-value-function", title="State-action value function", mins=11, tag="maths",
    lede="Q(s, a) — the single most important object in the week. Once you have it, the optimal policy is "
         "free.",
    body=(
        pretest("""<p>You want one number that says how good it is to take action <b>a</b> from state <b>s</b>. <b>Guess what it must account for</b> beyond the immediate reward.</p>""",
        """<p>Watch for the circular-looking definition — “then behave optimally” — and for why that is not a problem.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>Q(s, a) answers a very specific question:</p>
<p><b>“If I am here, and I do this one thing, and after that I play perfectly forever — how much do I get
in total?”</b></p>
<p>Notice the odd shape of it. The first move can be anything, even a silly one. Everything after that is
assumed to be optimal.</p>
<p>Why define it so strangely? Because it makes choosing trivially easy. Work out Q for each action you
could take, and take whichever number is bigger. That is the whole decision.</p>""")

        + h2("🔢", "The maths, decoded")
        + eqp([
            ('<var class="hl-a">Q</var>(<var>s</var>, <var>a</var>)', "q-function", "how good is this action"),
            ' <span class="op">=</span> the return if you start in <var>s</var>, take <var>a</var> once, then behave optimally',
        ], "the state-action value function — click it", small=True)
        + eqp([
            '<var>π</var>*(<var>s</var>) <span class="op">=</span> ',
            ('<span class="op">arg max</span><sub><var>a</var></sub>', "argmax-f0", "which action, not how good it is"),
            ' <var class="hl-a">Q</var>(<var>s</var>, <var>a</var>) &nbsp;&nbsp;&nbsp;&nbsp; <var>V</var>(<var>s</var>) <span class="op">=</span> <span class="op">max</span><sub><var>a</var></sub> <var class="hl-a">Q</var>(<var>s</var>, <var>a</var>)',
        ], "and both the policy and the state value fall straight out of it — click it")
        + decode([
            ("Q", "“Q”, or the Q-function", "Also called the optimal action-value function, and often written Q*."),
            ("“then behave optimally”", "“the circular bit”", "It refers to itself: Q is defined in terms of optimal behaviour, which is defined by Q. The Bellman equation (next lesson) is what makes this well-defined rather than circular."),
            ("arg max<sub>a</sub>", "“the action with the biggest Q”", "Not the value — the <em>action</em>. This is how a policy is read off a Q table."),
            ("V(s)", "“the state value”", "The best you can do from s, which is the maximum of Q over the available actions."),
        ])
        + key("""<p><b>If you know Q, you know everything.</b> The optimal policy is “look at the numbers,
take the bigger one”. This is why nearly every algorithm in the week is really an algorithm for
<em>estimating Q</em>.</p>""")

        + h2("🎬", "Watch it move")
        + demo("qfunction", "Q for every state and action on the rover",
               "drag γ and watch the values — and the arrows — respond")

        + h2("🧮", "The numbers, which are worth checking by hand")
        + table(["State", "Q(s, ←)", "Q(s, →)", "V(s)", "π*(s)"],
                [["2", "<b>50</b>", "12.5", "50", "←"],
                 ["3", "<b>25</b>", "6.25", "25", "←"],
                 ["4", "<b>12.5</b>", "10", "12.5", "←"],
                 ["5", "6.25", "<b>20</b>", "20", "→"]])
        + """<p>Check one yourself. Q(2, ←): from state 2 you move to state 1, collecting R(2) = 0 now and
then 100 one step later. 0 + 0.5 × 100 = <b>50</b>. ✓</p>
<p>And Q(4, →) = 10: move to state 5, then behave optimally — which from state 5 means going right for a
value of 20. So 0 + 0.5 × 20 = 10. Notice that computing Q for a “bad” first move still assumes good play
afterwards.</p>"""

        + explain("""<p>Q is defined as “take a, then behave optimally” — using optimal behaviour in its own definition. <b>Why is that not circular?</b></p>""",
            """<p>Because the recursion bottoms out. Terminal states have a known value with no lookahead, and every other state is defined one step closer to them. The definition unrolls to something concrete rather than chasing itself forever.</p>""")
        + h2("🕳", "Traps")
        + trap("""<p><b>Thinking Q(s, a) assumes you keep taking action a.</b> It does not. Only the
<em>first</em> action is a; everything after is optimal.</p>""")
        + trap("""<p><b>Confusing Q and V.</b> Q takes a state <em>and</em> an action. V takes only a state,
and equals the max of Q over actions.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Q(4, ←) = 12.5 and Q(4, →) = 10. What is π*(4), and what is V(4)?",
             "<p>π*(4) = <b>←</b> (the larger Q). V(4) = <b>12.5</b> (the value of that larger Q).</p>"),
            ("Verify Q(3, ←) = 25 by hand.",
             "<p>From state 3, go left to state 2. Reward now is R(3) = 0. Then behave optimally from "
             "state 2, which is worth V(2) = 50. So 0 + 0.5 × 50 = <b>25</b>. ✓</p>"),
            ("Why does knowing Q make the policy trivial?",
             "<p>Because Q already accounts for all future consequences. Comparing two numbers is a "
             "complete decision — no lookahead, no search.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, section 3.6",
             "Optimal value functions, and the proof that greedy-with-respect-to-Q* is optimal."),
            ("lab", REPO + "/week3/optional-labs/State-action%20value%20function%20example.ipynb",
             "Optional lab: state-action value function",
             "In this repo. Change the rewards and γ and watch every Q value recompute."),
        ])
    )))

# ============================================================ 7
L.append(dict(
    slug="07-state-action-value-example", title="State-action value function example", mins=8, tag="core",
    lede="Change the rewards. Change γ. Watch the optimal policy flip. This is the lesson where the "
         "numbers stop being abstract.",
    body=(
        pretest("""<p>Change the terminal reward from 40 to 400. <b>Guess what happens to the policy</b> in the states far from it.</p>""",
        """<p>Watch for how far the influence reaches, and how γ controls that reach.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>This is the lesson where you get to break things and watch what happens.</p>
<p>Move the reward at the far end up and down. Turn the patience dial &gamma; towards 0 and towards
1. Every time you do, the little arrows showing the best move can flip &mdash; sometimes all of them
at once, sometimes just the one in the middle.</p>
<p>Nothing here is new. It is the same six squares as the last three lessons. The point is to feel
that these numbers are not fixed facts about the world: they are consequences of the reward you
chose and how impatient you decided to be.</p>""")

        +h2("🎬", "Watch it move")
        + demo("qexample", "Drag the rewards and γ",
               "the arrows above the strip are the optimal policy — watch where they flip")

        + h2("🧪", "Three experiments worth running")
        + grid3(
            card("<h3>1 · Raise the right reward</h3><p>Set state 6 to 200. States 4 and 5 both switch to "
                 "going right. The dividing line moves left.</p>"),
            card("<h3>2 · Raise γ to 0.9</h3><p>The distant 100 stops being so heavily discounted, so even "
                 "state 5 becomes willing to make the long journey left.</p>"),
            card("<h3>3 · Drop γ to 0.2</h3><p>Only what is immediately nearby matters. The agent becomes "
                 "extremely short-sighted and dives for whichever end is closer.</p>"))
        + key("""<p>The optimal policy is a function of the <b>reward function and γ together</b>, not of
either alone. This is why reward design is the hard part of applying RL: you are not specifying the
behaviour, you are specifying an objective and hoping the behaviour that maximises it is the one you
wanted.</p>""")

        + h2("🔬", "Reward shaping, and how it goes wrong")
        + """<p>Since behaviour follows from the reward function, people try to design rewards that
encourage what they want. This is called <b>reward shaping</b>, and it has a rich literature of
failures:</p>
<ul>
<li>A boat-racing agent rewarded for collecting power-ups learned to spin in circles hitting the same
respawning power-ups forever, never finishing the race — and scored higher than human players.</li>
<li>Robots rewarded for “distance travelled” learn to fall over in the right direction.</li>
<li>A cleaning robot rewarded for “no visible mess” may learn to cover the mess up.</li>
</ul>
<p>The general name is <b>specification gaming</b>: the agent maximises exactly what you wrote down, which
turns out not to be what you meant.</p>"""

        + h2("✅", "Check yourself")
        + quiz([
            ("Set R(6) = 40 → 200 with γ = 0.5. What happens to π*(4)?",
             "<p>Q(4, →) becomes 0.5 × (0.5 × 200) = 50, beating Q(4, ←) = 12.5. State 4 <b>flips to "
             "going right</b>.</p>"),
            ("With γ = 0.9, what is Q(5, ←)?",
             "<p>0.9 × V(4), and V(4) itself rises with γ. Try it in the demo — at γ = 0.9 the far reward "
             "is worth 0.9³ × 100 = 72.9 from state 4, so the whole strip prefers going left.</p>"),
            ("Why is reward design considered the hard part of applied RL?",
             "<p>Because the agent optimises precisely what you specify, including loopholes you did not "
             "notice. The behaviour you get is a consequence of the reward function, not of your "
             "intentions.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("docs", "https://openai.com/index/faulty-reward-functions/",
             "OpenAI — Faulty Reward Functions in the Wild",
             "The boat-racing agent, with video. Two minutes, and it makes the point permanently."),
            ("paper", "https://arxiv.org/abs/1606.06565",
             "Amodei et al. (2016) — Concrete Problems in AI Safety",
             "Reward hacking, side effects, safe exploration. Still the best short introduction to why this is hard."),
            ("paper", "https://people.eecs.berkeley.edu/~pabbeel/cs287-fa09/readings/NgHaradaRussell-shaping-ICML1999.pdf",
             "Ng, Harada & Russell (1999) — Policy invariance under reward transformations",
             "The theory of reward shaping done safely: which changes provably do not alter the optimal policy."),
        ])
    )))

# ============================================================ 8
L.append(dict(
    slug="08-bellman-equation", title="The Bellman equation", mins=12, tag="maths",
    lede="One line that defines Q in terms of itself. Every reinforcement learning algorithm ever written "
         "is built on it.",
    body=(
        pretest("""<p>Any long journey splits into “this step” plus “the rest”. <b>Guess how that idea becomes an equation for Q.</b></p>""",
        """<p>Watch for the two halves: what you get now, plus the discounted best you can do next.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>How much is today worth?</p>
<p><b>What you get today</b>, plus <b>how good tomorrow will be</b> — slightly discounted, because
tomorrow is not today.</p>
<p>That is the whole equation. Every long journey splits into “this step” plus “the rest of the journey”.
And “the rest of the journey” is the same kind of question, one step smaller — so the same rule applies
again.</p>""")

        + h2("🔢", "The maths, decoded")
        + eqp([
            ('<var class="hl-a">Q</var>(<var>s</var>, <var>a</var>)', "q-function", "how good is this action"),
            ' <span class="op">=</span> ',
            ('<var class="hl-g">R</var>(<var>s</var>)', "reward-r", "right now"),
            ' <span class="op">+</span> ',
            ('<var class="hl-m">γ</var>', "gamma-discount", "the discount factor"),
            ' ',
            ('<span class="op">max</span><sub><var>a</var>′</sub> <var class="hl-b">Q</var>(<var>s</var>′, <var>a</var>′)',
             "future-value", "best you can do next"),
        ], "the Bellman equation — click any part")
        + decode([
            ("<var class='hl-g'>R</var>(<var>s</var>)", "“the reward right now”", "What you collect for being in the state you are in. The <b>immediate</b> half."),
            ("<var>s</var>′", "“s prime”", "The state you land in after taking action a. Prime always means “next”."),
            ("<var>a</var>′", "“a prime”", "The action you would take from there."),
            ("max<sub>a′</sub> Q(s′, a′)", "“the best you can do from there”", "This is V(s′). The <b>future</b> half."),
            ("<var class='hl-m'>γ</var>", "“discount it”", "The future half is worth slightly less because it happens later."),
        ])
        + key("""<p>Two halves: <b>what you get now</b>, plus <b>the discounted value of the best thing you
can do next</b>. Every RL algorithm is a different strategy for making an estimate of Q satisfy this
equation.</p>""")

        + h2("🎬", "Watch it move")
        + demo("bellman", "Pick a state and an action, and watch the equation assemble",
               "each coloured box is one term")

        + h2("🧮", "Worked, on state 4")
        + """<p>Q(4, ←): from state 4, going left lands you in state 3.</p>
<ul>
<li>R(4) = 0 — nothing collected right now.</li>
<li>The best you can do from state 3 is V(3) = max(25, 6.25) = 25.</li>
<li>So Q(4, ←) = 0 + 0.5 × 25 = <b>12.5</b>. ✓</li>
</ul>
<p>At a terminal state there is no “next”, so the second term vanishes and Q(s, a) = R(s). That is the
base case that stops the recursion — the same structural role as the leaf in a decision tree.</p>"""

        + explain("""<p>Q(4, ←) came out as 0 + 0.5 × 25. <b>Why is the whole future compressed into that single number 25?</b></p>""",
            """<p>Because V(3) already <em>is</em> the whole future from state 3, played optimally. The recursion means you never look further than one step: everything beyond is summarised in the value of where you land.</p>""")
        + h2("🔬", "Why this makes the circular definition work")
        + """<p>Lesson 6 defined Q in terms of “behaving optimally afterwards”, which sounds circular. The
Bellman equation turns that circularity into something computable: it is a system of equations that Q must
satisfy, and it has exactly one solution.</p>
<p>You can find it by starting with any guess and repeatedly applying the equation as an update — each
application brings you closer, guaranteed. That procedure is <b>value iteration</b>, and it is precisely
what computes the numbers in every demo on this page.</p>"""
        + note("""<p>Richard Bellman introduced this in the 1950s while working on <b>dynamic programming</b>
— a name he reportedly chose because it sounded impressive to a research-funding department that was
hostile to mathematics. The technique long predates machine learning and shows up everywhere from route
planning to sequence alignment.</p>""", "Where the name comes from")

        + h2("🕳", "Traps")
        + trap("""<p><b>Forgetting the max.</b> It is max over the <em>next</em> action a′, not over a.
The action you are evaluating is fixed; the future one is optimised.</p>""")
        + trap("""<p><b>Using R(s′) instead of R(s).</b> In this course’s convention the reward belongs to
the state you are <em>leaving</em>. Other texts use R(s, a, s′). Both are internally consistent; mixing
them is not.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Compute Q(2, →) with γ = 0.5.",
             "<p>Going right from 2 lands in state 3, where V(3) = 25. So Q(2, →) = 0 + 0.5 × 25 = "
             "<b>12.5</b>.</p>"),
            ("What is Q(s, a) at a terminal state?",
             "<p>Just <b>R(s)</b>. There is no next state, so the second term disappears.</p>"),
            ("Why is the Bellman equation recursive, and why does that not make it circular?",
             "<p>Q appears on both sides, so it is defined in terms of itself. It is not circular because "
             "the equation has a unique solution, reachable by repeated application from any starting "
             "guess — value iteration.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, chapter 4 — Dynamic Programming",
             "Value iteration and policy iteration: the exact-solution methods that this equation makes possible."),
            ("paper", "https://www.jstor.org/stable/24900506",
             "Bellman (1957) — A Markovian Decision Process",
             "The original. Written before anyone thought of it as machine learning."),
            ("video", "https://www.youtube.com/watch?v=aNuOLwojyfg",
             "David Silver — RL Course, lecture 2 (MDPs)",
             "DeepMind’s course. The Bellman equation derived properly, with the matrix form."),
        ])
    )))

# ============================================================ 9
L.append(dict(
    slug="09-stochastic-environments", title="Random (stochastic) environments", mins=9, tag="optional",
    lede="What if the rover slips? One word — expected — and the whole framework survives intact.",
    body=(
        pretest("""<p>You command “left” and the rover goes right 10% of the time. <b>Guess what has to change in the Bellman equation.</b></p>""",
        """<p>Watch for expected value replacing a single certain outcome, and for why an unreliable world is worth less to be in.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>You tell the rover to go left. But the ground is icy, and 10% of the time it slides
right instead.</p>
<p>Now you cannot say “if I go left I will definitely reach state 3”. You can only say “probably state 3,
occasionally state 5”.</p>
<p>So you stop asking “what will I get?” and start asking <b>“what will I get on average?”</b> — averaged
over all the ways it could turn out, weighted by how likely each one is.</p>""")

        + h2("🎬", "Watch it move")
        + demo("stochastic", "Add a misstep probability and watch every value fall",
               "an unreliable world is worth less to be in")

        + h2("🔢", "The maths, decoded")
        + eqp([
            ('<var>Q</var>(<var>s</var>, <var>a</var>)', "q-function", "how good is this action"),
            ' <span class="op">=</span> ',
            ('<var>R</var>(<var>s</var>)', "reward-r", "right now"),
            ' <span class="op">+</span> ',
            ('<var>γ</var>', "gamma-discount", "the discount factor"),
            ' <var class="hl-a">E</var><span class="paren">[</span> ',
            ('<span class="op">max</span><sub><var>a</var>′</sub> <var>Q</var>(<var>s</var>′, <var>a</var>′)', "future-value", "best you can do next"),
            ' <span class="paren">]</span>',
        ], "the same equation, with an expectation around the future term — click a part")
        + decode([
            ("<var class='hl-a'>E</var>[ … ]", "“the expected value of”", "A weighted average over every possible next state, weighted by its probability."),
            ("expected return", "“the average over many attempts”", "Not what will happen on one run — what happens on average over very many runs."),
            ("P(s′ | s, a)", "“the transition probabilities”", "The chance of landing in s′ given that you took a in s. In this example: 0.9 intended, 0.1 slipped."),
        ])
        + key("""<p>That single <b>E</b> is the only change in the entire framework. Everything else — the
policy, the Q function, the algorithm — carries over untouched. The maximisation target changes from “the
return” to “the <b>expected</b> return”.</p>""")

        + h2("🔬", "What the demo shows")
        + """<p>Every value falls as the misstep probability rises. V(4) drops from 12.5 with perfect
control to noticeably less at a 10% misstep rate.</p>
<p>This is correct and not merely a numerical artefact: a world you cannot fully control genuinely is
worth less to be in, because some of the time your good decisions get overruled by chance.</p>
<p>At high misstep probabilities the optimal policy itself can change — it becomes worth heading towards
whichever reward is more reliably reachable, rather than the larger one.</p>"""

        + h2("🕳", "Traps")
        + trap("""<p><b>Confusing a stochastic environment with a stochastic policy.</b> Here the
<em>world</em> is random; the policy still deterministically says “go left”. A stochastic policy is a
different thing — the agent choosing randomly on purpose.</p>""")
        + trap("""<p><b>Evaluating a stochastic policy on one episode.</b> One run tells you almost nothing.
Average over many.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("90% chance of landing in a state worth 100, 10% chance of one worth 0. Expected value?",
             "<p>0.9 × 100 + 0.1 × 0 = <b>90</b>.</p>"),
            ("Why do all the values fall as the misstep probability rises?",
             "<p>Because some fraction of your intended actions get overruled, so on average you collect "
             "less. Uncertainty has a cost.</p>"),
            ("What is the only change to the Bellman equation?",
             "<p>The future term becomes an <b>expectation</b> over next states. Nothing else changes.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, section 3.6",
             "The Bellman optimality equation in its general stochastic form — which is the version everything else is derived from."),
        ])
    )))

# ============================================================ 10
L.append(dict(
    slug="10-continuous-state-spaces", title="Continuous state spaces", mins=13, tag="core",
    lede="Six squares was a teaching example. Real problems have states made of real numbers — and a "
         "lookup table stops being possible.",
    body=(
        pretest("""<p>The rover had six states. A lunar lander has position, velocity, angle and spin — all continuous. <b>Guess why a table of Q values stops working.</b></p>""",
        """<p>Watch for what replaces the table, and why that is where neural networks enter.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>The rover had six possible positions. You could write all six on a piece of paper, with
two Q values each — twelve numbers, done.</p>
<p>A truck is at position 12.34 metres, heading 0.7 radians, moving 8.2 metres per second. How many
possible states is that? <b>Infinitely many.</b> You cannot make a list.</p>
<p>So you stop storing Q in a table and start <b>computing</b> it. Feed the numbers into a function and get
Q back out. That function is going to be a neural network.</p>""")

        + h2("🎬", "Watch it move")
        + demo("continuousstates", "Six squares versus six real numbers",
               "the truck's state changes continuously — no two moments are ever the same state")

        + h2("🔢", "What a continuous state looks like")
        + table(["System", "State vector", "Size"],
                [["Mars rover", "which of 6 squares", "1 discrete value"],
                 ["Self-driving truck", "x, y, θ, ẋ, ẏ, θ̇", "6 real numbers"],
                 ["Autonomous helicopter", "x, y, z, roll, pitch, yaw, and all six rates of change", "12 real numbers"],
                 ["Lunar lander", "x, y, ẋ, ẏ, θ, θ̇, l, r", "8 numbers (6 real, 2 binary)"]])
        + decode([
            ("continuous state", "“made of real numbers”", "s ∈ ℝ<sup>n</sup> instead of s ∈ {1, …, 6}."),
            ("θ̇", "“theta dot”", "The rate of change of θ. A dot over a symbol means “per unit time” — standard physics notation."),
            ("function approximation", "“compute Q instead of storing it”", "The technical name for the whole idea. The network approximates the Q function."),
        ])
        + key("""<p>This is the moment the two halves of the specialization meet. Neural networks were the
tool for “compute a number from a vector of numbers”, and that is exactly what a continuous-state Q
function needs.</p>""")

        + h2("🔬", "Why not just chop it into bins?")
        + """<p>You could discretise: split each dimension into 100 buckets and use a table. For a 6-D state
that is 100⁶ = a trillion cells, most of which you will never visit. For the helicopter’s 12 dimensions it
is 100¹² — more cells than atoms in a building.</p>
<p>This is the <b>curse of dimensionality</b>, and it is why function approximation is not a convenience
but a necessity. A neural network also <em>generalises</em>: it learns that states near each other tend to
have similar Q values, which a table can never do.</p>"""

        + h2("🧮", "Why you cannot just chop it into bins")
        + """<p>The Mars rover had 6 states, so <var>Q</var> fitted in a 6 × 2 table. The lunar
lander’s state is 8 continuous numbers. The obvious repair — divide each into bins — runs into this:</p>"""
        + table(["bins per dimension", "states in the table (bins⁸)", ""],
                [["3", "6,561", "far too coarse to fly with"],
                 ["10", "<b>100,000,000</b>", "100 million rows"],
                 ["20", "<b>25,600,000,000</b>", "25.6 billion"]])
        + """<p>Ten bins per axis is already crude — it cannot tell a 5° tilt from a 30° one — and it
already needs a hundred million table entries. Worse than the storage: each entry would have to be
<em>visited</em>, repeatedly, to learn its value. The lander would have to experience every one of
those hundred million situations many times over.</p>
<p>This is the curse of dimensionality, and the exponent is what kills it. Adding one more sensor
does not add rows, it multiplies them by 10.</p>
<p>A neural network never enumerates states. It takes the 8 numbers as input and outputs
<var>Q</var>, so it must <em>generalise</em> — and generalising is exactly what a table cannot do.
Two nearly identical states are unrelated rows in a table and near-identical inputs to a network.</p>"""
        + explain("""<p>A table has one independent number per state, which sounds like an advantage —
it can represent absolutely any Q function. <b>Why is that flexibility fatal here?</b></p>""",
                  """<p>Because every one of those numbers must be learned from experience of that
exact state, and nothing learned about one row ever helps another. A table has no notion that
“tilted 10° at 3 m/s” resembles “tilted 11° at 3 m/s” — they are unrelated cells, so the lesson must
be paid for twice. Unlimited flexibility with no sharing means the data required grows as fast as
the table does. The network’s inability to represent arbitrary functions is precisely what forces it
to assume nearby states behave alike, and that assumption is true here, so it is worth far more than
the flexibility it costs.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Why can't you store Q in a table for a continuous state space?",
             "<p>There are infinitely many states. Even discretised, the table grows exponentially with "
             "the number of dimensions and you would never visit most of it.</p>"),
            ("What does a neural network give you that a table cannot?",
             "<p><b>Generalisation.</b> Having seen one state, it makes sensible predictions for nearby "
             "states it has never visited. A table has no notion of “nearby”.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, chapter 9 — On-policy Prediction with Approximation",
             "Function approximation done properly, including why it breaks some of the guarantees from the tabular case."),
        ])
    )))

# ============================================================ 11
L.append(dict(
    slug="11-lunar-lander", title="The lunar lander", mins=9, tag="core",
    lede="The assignment problem, stated fully. Eight state numbers, four actions, and a reward function "
         "that is doing more work than it looks.",
    body=(
        pretest("""<p>Eight numbers in, four possible actions. <b>Guess how you would design the reward</b> so the lander learns to land rather than to hover forever.</p>""",
        """<p>Watch for how much of RL is reward design, and how easily a plausible reward produces absurd behaviour.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>Land a little spaceship gently on a landing pad. You have three thrusters: one pointing
down, one pointing left, one pointing right. You can also do nothing and just fall.</p>
<p>Land softly on the pad: big prize. Crash: big penalty. Every puff of the engine costs a tiny bit,
because fuel is not free.</p>
<p>Nobody tells you the correct thruster to fire at any moment. You just try, crash a few thousand times,
and gradually work it out.</p>""")

        + h2("🎬", "Watch it move")
        + demo("lunarlander", "The state vector, the actions, and the reward function",
               "eight numbers in, one of four actions out")

        + h2("🔢", "The state — eight numbers")
        + table(["Symbol", "Meaning", "Type"],
                [["x", "horizontal position relative to the pad", "real"],
                 ["y", "height above the ground", "real"],
                 ["ẋ", "horizontal velocity", "real"],
                 ["ẏ", "vertical velocity (how fast it is falling)", "real"],
                 ["θ", "tilt angle", "real"],
                 ["θ̇", "angular velocity (how fast it is spinning)", "real"],
                 ["l", "left leg touching the ground?", "<b>binary</b>"],
                 ["r", "right leg touching the ground?", "<b>binary</b>"]])
        + """<p>Four actions: do nothing, fire the left thruster, fire the main engine, fire the right
thruster.</p>"""

        + h2("🎯", "The reward function, which is the real design work")
        + table(["Event", "Reward"],
                [["getting to the landing pad", "+100 to +140, depending on how close"],
                 ["crashing", "−100"],
                 ["a soft landing", "+100"],
                 ["each leg touching down", "+10"],
                 ["firing the main engine", "−0.3 per step"],
                 ["firing a side thruster", "−0.03 per step"]])
        + key("""<p>Look at what that reward function is quietly encoding: <b>get there, do not crash, land
level, and do not waste fuel</b> — four competing objectives, balanced by their relative magnitudes.
Writing this is far more of an art than writing the algorithm, and it is where most of the real
engineering time goes.</p>""")

        + h2("🔬", "Why the numbers are the sizes they are")
        + """<p>The fuel penalties are deliberately tiny (−0.03, −0.3) compared to the landing rewards
(±100). If fuel cost too much, the optimal policy would be to switch everything off and drop like a stone —
crashing is only −100, and hovering for a hundred steps costs −30.</p>
<p>Make fuel cheaper still and the lander hovers indefinitely, burning fuel while never quite committing to
landing, because landing risks the −100. The balance between these numbers <em>is</em> the specification of
the behaviour, and small changes produce qualitatively different pilots.</p>"""

        + h2("🕳", "Traps")
        + trap("""<p><b>Forgetting the leg-contact flags are binary.</b> They are 0 or 1 while everything
else is a real number. Feeding raw unnormalised state into a network mixes scales — the C2 W1 scaling
lesson applies.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Why include velocities in the state and not just positions?",
             "<p>Because of the Markov property. Position alone cannot tell you whether the lander is "
             "descending gently or plummeting — and the correct action differs completely.</p>"),
            ("Why is the fuel penalty so much smaller than the crash penalty?",
             "<p>So that saving fuel never becomes worth risking a crash. The relative sizes encode the "
             "priority ordering of the objectives.</p>"),
            ("What would happen if you removed the fuel penalty entirely?",
             "<p>The lander would have no incentive to be efficient — it might hover indefinitely, or "
             "fire everything constantly. The penalty is what makes it commit to landing.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("docs", "https://gymnasium.farama.org/environments/box2d/lunar_lander/",
             "Gymnasium — LunarLander-v2",
             "The exact environment, with the precise reward function and termination conditions."),
            ("lab", REPO + "/week3/C3W3A1/C3_W3_A1_Assignment.ipynb",
             "Week 3 assignment: deep Q-learning for the lunar lander",
             "In this repo. You implement the loss function and watch it learn to land."),
        ])
    )))

# ============================================================ 12
L.append(dict(
    slug="12-learning-the-state-value-function", title="Learning the state-value function", mins=16, tag="core",
    lede="The algorithm itself. Turn reinforcement learning into supervised learning by manufacturing your "
         "own training targets — from the network you are training.",
    body=(
        pretest("""<p>You need training data for Q, but Q is what you are trying to learn. <b>Guess how you escape that circle.</b></p>""",
        """<p>Watch for using your current guess to produce a better target — the trick at the heart of the whole method.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>Here is the trick that makes the whole thing work.</p>
<p>You want a network that predicts Q(s, a). But you have no labels — nobody knows the true Q.</p>
<p>So you <b>invent</b> them. Fly the lander badly. Write down every moment: “I was here, I did this, I got
this reward, I ended up there.” Then use the Bellman equation to make a target:
<em>y = the reward I actually got, plus γ times whatever my current network thinks the new state is
worth.</em></p>
<p>Your targets are partly guesses. But the reward part is real, and true information leaks in from there
one step at a time until the guesses become correct.</p>""")

        + h2("🎬", "Watch it move")
        + demo("dqn", "The six steps, and the replay buffer filling up",
               "each cycle makes the targets slightly less wrong")

        + h2("🔢", "The algorithm")
        + """<ol>
<li>Initialise the neural network with <b>random weights</b> — a terrible guess at Q(s, a).</li>
<li>Repeat forever:
  <ul>
  <li>Take actions in the lunar lander. Store each (s, a, R(s), s′) tuple.</li>
  <li>Keep only the 10,000 most recent tuples — the <b>replay buffer</b>.</li>
  <li>Build a training set: <b>x = (s, a)</b> and <b>y = R(s) + γ max<sub>a′</sub> Q(s′, a′)</b>.</li>
  <li>Train Q<sub>new</sub> so that Q<sub>new</sub>(x) ≈ y. This is ordinary supervised learning.</li>
  <li>Set Q = Q<sub>new</sub>.</li>
  </ul>
</li>
</ol>"""
        + decode([
            ("replay buffer", "“the memory”", "The most recent 10,000 experiences. Training samples randomly from it rather than using the newest few."),
            ("the target y", "“a bootstrapped guess”", "R(s) is real, measured. max Q(s′, a′) is the network’s current estimate. Half fact, half guess."),
            ("bootstrapping", "“learning from your own estimates”", "Updating an estimate using another estimate. Peculiar, and it works."),
            ("Q = Q<sub>new</sub>", "“the swap”", "The targets are recomputed with the improved network next round, so they get better too."),
        ])
        + key("""<p>The reason it converges rather than spiralling: <b>R(s) is real</b>. Every target
contains one genuine measured reward. That true signal propagates backwards, one step per iteration, until
the estimates everywhere are anchored to reality.</p>""")

        + h2("🔬", "Why the replay buffer matters")
        + """<p>Two problems it solves, and both are serious:</p>
<ul>
<li><b>Correlation.</b> Consecutive frames are almost identical. Training on them in order violates the
i.i.d. assumption that supervised learning rests on, and the network oscillates. Sampling randomly from
10,000 stored experiences breaks the correlation.</li>
<li><b>Data efficiency.</b> Each expensive experience gets reused many times instead of being seen once
and discarded.</li>
</ul>
<p>Removing the replay buffer from DQN was tested in the original paper, and performance collapses. It is
not an optimisation — it is load-bearing.</p>"""

        + h2("🧮", "The network, and the training set it invents")
        + """<p>The assignment’s <var>Q</var>-network, counted:</p>"""
        + table(["Layer", "shape", "parameters"],
                [["Input", "8 (the state)", "—"],
                 ["Dense(64, relu)", "(8, 64)", "8 × 64 + 64 = 576"],
                 ["Dense(64, relu)", "(64, 64)", "64 × 64 + 64 = 4,160"],
                 ["Dense(4, linear)", "(64, 4)", "64 × 4 + 4 = 260"],
                 ["", "", "<b>4,996 total</b>"]])
        + """<p>Under five thousand parameters — smaller than the Week 1 digit classifier. The
difficulty in reinforcement learning has never been the network.</p>
<p>It is where the training data comes from. There is no labelled set; the agent manufactures one by
flying badly. Each experience is a tuple (s, a, R, s′), and the target is built from Bellman:</p>"""
        + eq("""<var>y</var> <span class="op">=</span> <var>R</var>
<span class="op">+</span> γ <span class="op">·</span> max<sub>a′</sub>
<var>Q̂</var>(<var>s</var>′, <var>a</var>′)""", "the label, computed from the network's own output")
        + """<p>Then it is ordinary supervised learning: input <var>s</var>, target <var>y</var>,
mean squared error. Except for one thing that has no counterpart anywhere else in this course —
<b>the labels are produced by the model being trained</b>. Improve <var>Q</var> and every target
changes, which is why the algorithm needs the frozen target network and the replay buffer to stay
stable at all.</p>"""
        + explain("""<p>Training a model on labels generated by that same model sounds circular — it
could confidently agree with itself about anything. <b>What stops it?</b></p>""",
                  """<p>The reward. Look at the target: <var>y</var> = <var>R</var> + γ·max
<var>Q̂</var>. Only the second term is the model’s own opinion; the first is a fact the environment
supplied. At a terminal state there is no second term at all, so those targets are pure reality —
and every step backwards from a terminal state carries a little of that reality with it, discounted
by γ. The circularity is real but it is anchored, and the anchor propagates outward from the states
where the truth is known. Remove the reward and the whole thing does collapse into
self-agreement.</p>""")

        + h2("🕳", "Traps")
        + trap("""<p><b>Expecting monotonic improvement.</b> RL training curves are famously spiky. The
agent gets better, then suddenly worse, then better. This is normal, and it is why people average over
several random seeds before believing anything.</p>""")
        + trap("""<p><b>Training on the most recent experiences only.</b> Highly correlated, and the network
forgets what it learned earlier. Sample randomly from the buffer.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Where does the target y come from, given that there are no labels?",
             "<p>From the Bellman equation: y = R(s) + γ max Q(s′, a′). The reward is real; the second "
             "term is the network's own current estimate.</p>"),
            ("Why does bootstrapping from your own estimates not just produce garbage?",
             "<p>Because R(s) is genuine measured information. Every target is anchored by one real "
             "reward, and that truth propagates outwards through the state space.</p>"),
            ("What breaks if you remove the replay buffer?",
             "<p>Consecutive experiences are highly correlated, so training becomes unstable and the "
             "network oscillates or diverges. It was one of the two key contributions of the DQN paper.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("paper", "https://www.nature.com/articles/nature14236",
             "Mnih et al. (2015) — Human-level control through deep RL",
             "The DQN paper. Algorithm 1 is precisely what you are implementing, plus a target network."),
            ("paper", "https://arxiv.org/abs/1312.5602",
             "Mnih et al. (2013) — Playing Atari with Deep Reinforcement Learning",
             "The earlier workshop version. Shorter, and arguably clearer."),
            ("paper", "https://arxiv.org/abs/1511.05952",
             "Schaul et al. (2015) — Prioritized Experience Replay",
             "Sample surprising experiences more often instead of uniformly. A large, cheap improvement."),
        ])
    )))

# ============================================================ 13
L.append(dict(
    slug="13-improved-architecture", title="Algorithm refinement: improved neural network architecture",
    mins=13, tag="core",
    lede="Move the actions from the input side to the output side. Four times less compute, for free.",
    body=(
        pretest("""<p>The first architecture outputs Q for one action, so four actions need four forward passes. <b>Guess the fix.</b></p>""",
        """<p>Watch for moving the actions to the output layer. One pass instead of four, millions of times per run.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>The obvious design: tell the network where you are <b>and</b> what you are thinking of
doing, and it gives you one number. But then, to choose between four actions, you have to ask it four
separate times.</p>
<p>Better design: tell it only where you are, and let it give you <b>four numbers at once</b> — one per
action. Ask once, get everything.</p>""")

        + h2("🎬", "Watch it move")
        + demo("dqnarch", "One output versus four",
               "count the forward passes at the bottom of each side")

        + h2("🔢", "The comparison")
        + table(["", "Naive", "Improved"],
                [["Input", "8 state + 4 one-hot action = 12", "<b>8 state only</b>"],
                 ["Output", "1 number: Q(s, a)", "<b>4 numbers: Q(s, a) for every a</b>"],
                 ["Passes per decision", "4", "<b>1</b>"],
                 ["Computing max Q(s′, a′)", "4 more passes", "<b>a max over 4 numbers you already have</b>"]])
        + key("""<p>The saving compounds. Every training step needs max<sub>a′</sub> Q(s′, a′) for the
target, and every action choice needs all four Q values. The improved architecture does both in one pass
instead of four — and this happens millions of times during training.</p>""")

        + h2("💻", "In Keras")
        + code("""
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

q_network = Sequential([
    Dense(64, activation='relu', input_shape=(state_size,)),   # 8 inputs
    Dense(64, activation='relu'),
    Dense(num_actions, activation='linear'),                   # 4 outputs, LINEAR
])
""")
        + warn("""<p>The output activation is <b>linear</b>, not sigmoid or softmax. Q values are unbounded
real numbers — they can be −200 or +140. Squashing them into 0…1 would destroy the information the Bellman
equation depends on.</p>""")

        + h2("🧮", "Counting the forward passes you save")
        + """<p>The naive design takes the state <em>and</em> the action as input and returns one
number. The improved design takes only the state and returns one number per action:</p>"""
        + table(["", "naive: Q(s, a) → 1 output", "improved: Q(s) → 4 outputs"],
                [["inputs", "8 state + 4 one-hot action = 12", "8"],
                 ["outputs", "1", "4"],
                 ["passes to evaluate one action", "1", "1 (read one output)"],
                 ["passes to find max<sub>a′</sub> Q(s′, a′)", "<b>4</b>", "<b>1</b>"]])
        + """<p>A factor of four, and it is not a micro-optimisation, because that max is not
occasional. It appears in <em>every single target</em>:
<var>y</var> = <var>R</var> + γ·max<sub>a′</sub> <var>Q̂</var>(<var>s</var>′, <var>a</var>′). Train
on a mini-batch of 64 experiences and the naive version needs 256 forward passes to build 64 targets;
the improved version needs 64.</p>
<p>In code the change is one number — the width of the final layer — and the shape of the input:</p>"""
        + code("""
Dense(units=num_actions, activation='linear')     # 4 outputs, not 1

max_qsa = tf.reduce_max(target_q_network(next_states), axis=-1)   # one call, all actions
""")
        + """<p><code>reduce_max</code> along the last axis is the whole “try every action” step,
vectorised away exactly as in Course 2 Week 1.</p>"""
        + explain("""<p>Both designs compute the same <var>Q</var> values. <b>Why does the improved
one also tend to <em>learn</em> better, not merely faster?</b></p>""",
                  """<p>Because the four outputs share every hidden layer. Whatever the network
figures out about reading a state — “this tilt plus this velocity is dangerous” — is computed once
and used by all four action-values, so evidence about one action improves the representation used to
judge the others. In the naive design the action is just another input feature, and the network has
to rediscover the same state-reading logic separately for each action’s corner of the input space.
Shared structure means shared learning, which is the same argument that makes multi-output networks
preferable to N separate binary classifiers.</p>""")

        + h2("🕳", "Traps")
        + trap("""<p><b>Using softmax on the output.</b> These are values, not probabilities. They do not
sum to 1 and they must not be normalised against each other.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Why is one forward pass instead of four a big deal?",
             "<p>Because it happens on every action choice <em>and</em> in every target computation — "
             "millions of times per training run. A 4× saving on the dominant cost.</p>"),
            ("Why linear activation on the output layer?",
             "<p>Q values are unbounded real numbers. Any squashing function would clip them and break "
             "the Bellman relationship.</p>"),
            ("With the improved architecture, how do you compute max Q(s′, a′)?",
             "<p>One forward pass on s′, then <code>np.max(...)</code> over the four outputs. No extra "
             "network calls at all.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("paper", "https://arxiv.org/abs/1511.06581",
             "Wang et al. (2015) — Dueling Network Architectures for Deep RL",
             "A further refinement: split the output into “how good is this state” and “how much better is each action”."),
        ])
    )))

# ============================================================ 14
L.append(dict(
    slug="14-epsilon-greedy", title="Algorithm refinement: ε-greedy policy", mins=10, tag="core",
    lede="If you only ever do what you currently believe is best, you never discover that you were wrong.",
    body=(
        pretest("""<p>Always take the action your current Q says is best. <b>Guess what you might never discover</b> — and what small change fixes it.</p>""",
        """<p>Watch for the explore/exploit tension, and for what ε is doing about it.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>You always order the same thing at the restaurant because you know it is good. But there
are forty other dishes and one of them might be better — you will never find out.</p>
<p>So make a rule: <b>most of the time, order your favourite. Occasionally, order something random.</b></p>
<p>For the lunar lander this matters enormously. Its network starts with random weights, so it might
believe firing the main engine is terrible. If it never tries, it never learns otherwise, and the belief
never gets corrected.</p>""")

        + h2("🎬", "Watch it move")
        + demo("epsilongreedy", "Drag ε and watch the choices",
               "at ε = 0 it always takes the same action; at ε = 1 it is pure noise")

        + h2("🔢", "The policy")
        + eqp([
            'with probability <span class="op">1 −</span> <var class="hl-a">ε</var>:&nbsp; take ',
            ('<span class="op">arg max</span><sub><var>a</var></sub> <var>Q</var>(<var>s</var>, <var>a</var>)', "argmax-f0", "the action with the highest Q"),
            ' &nbsp;&nbsp;·&nbsp;&nbsp; with probability <var class="hl-a">ε</var>:&nbsp; pick at random',
        ], "the ε-greedy policy — click it", small=True)
        + decode([
            ("<var class='hl-a'>ε</var>", "“epsilon”", "The fraction of the time you deliberately ignore your own advice. Typically 0.01 to 1.0."),
            ("greedy", "“take the best you know”", "Exploitation. Slightly confusingly, this is the <em>1 − ε</em> part."),
            ("exploration", "“try something new”", "The ε part. It is how you find out that a belief was wrong."),
            ("ε decay", "“start curious, become confident”", "Begin at ε = 1.0 (all random) and decay towards 0.01 as Q becomes trustworthy."),
        ])
        + key("""<p>The exploration/exploitation trade-off is one of the genuinely fundamental problems in
RL, and ε-greedy is the crudest possible answer to it. It works surprisingly well, which is why it is
still the default.</p>""")

        + h2("🔬", "Why decay ε")
        + """<p>Early on, Q is random noise. Following it greedily is pointless, so ε should be near 1 —
explore almost everything.</p>
<p>Later, Q is genuinely informative. Random actions now mostly waste time and crash the lander, so ε
should be small — but not zero, because there may still be corners of the state space you have not
visited.</p>
<p>The assignment uses ε = 1.0 decaying multiplicatively to a floor of 0.01. Andrew notes something worth
remembering: in reinforcement learning, a badly chosen hyperparameter does not merely slow you down by a
factor of three the way it might in supervised learning — it can make the difference between learning and
never learning at all. RL is genuinely more brittle.</p>"""

        + h2("🕳", "Traps")
        + trap("""<p><b>ε = 0 from the start.</b> The agent locks onto whatever its random initialisation
happened to favour and never revises it. This is the single most common reason a DQN “does not
learn”.</p>""")
        + trap("""<p><b>ε staying at 1.0.</b> Pure random play forever. It collects experience but never
exploits what it learned, so performance never improves.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Q = [12, 31, 24, 9] and ε = 0.05. What happens?",
             "<p>95% of the time it takes action 2 (Q = 31). 5% of the time it picks uniformly at random "
             "from all four — including action 2.</p>"),
            ("Why start at ε = 1.0?",
             "<p>Because at the start Q is random noise. Following it greedily is no better than random, "
             "and exploring widely gathers the varied experience the network needs.</p>"),
            ("Why not decay ε all the way to 0?",
             "<p>Because there may be states you have never visited whose Q estimates are still wrong. A "
             "small floor (0.01) keeps a little exploration alive indefinitely.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto, chapter 2 — Multi-armed Bandits",
             "The exploration/exploitation trade-off in its purest form, with ε-greedy, UCB and Thompson sampling compared."),
            ("paper", "https://arxiv.org/abs/1706.10295",
             "Fortunato et al. (2017) — Noisy Networks for Exploration",
             "Add learnable noise to the weights instead of choosing randomly. A more principled successor to ε-greedy."),
        ])
    )))

# ============================================================ 15
L.append(dict(
    slug="15-minibatch-soft-updates", title="Algorithm refinement: mini-batch and soft updates",
    mins=9, tag="core",
    lede="Two small changes that turn “sometimes works” into “reliably works”. Both are about not moving "
         "too fast.",
    body=(
        pretest("""<p>Training on all stored experience every step is too slow, and replacing the network wholesale is unstable. <b>Guess the two refinements.</b></p>""",
        """<p>Watch for a subset per step, and for blending rather than replacing the weights.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p><b>Mini-batch:</b> you have ten thousand memories. Looking at all of them before taking
one small step is exhausting. Look at a random thousand instead — a slightly worse decision, made ten times
faster. Ten fast steps beat one perfect one.</p>
<p><b>Soft update:</b> when the new network seems better, do not throw the old one away and swap. Blend
them: keep 99% of the old and mix in 1% of the new. Because the network is being used to compute its own
targets, changing it suddenly means every target lurches at once.</p>""")

        + h2("🎬", "Watch it move")
        + demo("minibatch", "The subset, and the blend",
               "drag τ from 0.001 to 1 and read what each end means")

        + h2("🔢", "Mini-batch")
        + table(["", "Batch gradient descent", "Mini-batch"],
                [["Examples per step", "all m", "a random subset (1,000 or 64)"],
                 ["Cost per step", "high", "<b>low</b>"],
                 ["Steps per minute", "few", "<b>many</b>"],
                 ["Direction of each step", "exact", "noisy, but right on average"]])
        + """<p>This is not an RL-specific idea — it is how essentially all deep learning is trained.
Andrew introduces it here because the replay buffer makes it unavoidable, but it applies equally to
everything in Course 2.</p>"""
        + note("""<p>The noise in mini-batch gradients is not purely a cost. It helps the optimiser escape
shallow local minima and saddle points, which is part of why mini-batch training often <em>generalises</em>
better than full-batch, not merely faster.</p>""", "The noise is partly a feature")

        + h2("🔢", "Soft update")
        + eqp([
            ('<var>W</var> <span class="op">:=</span>', "assign-op", "becomes, not equals"),
            ' <var class="hl-a">τ</var> <var>W</var><sub>new</sub> <span class="op">+</span> (1 <span class="op">−</span> <var class="hl-a">τ</var>) <var>W</var><sub>old</sub> &nbsp;&nbsp;&nbsp; with <var class="hl-a">τ</var> <span class="op">=</span> 0.01',
        ], "blend, do not replace — click it")
        + decode([
            ("<var class='hl-a'>τ</var>", "“tau”", "How much of the new network to mix in. 0.01 is typical — 1% new, 99% old."),
            ("τ = 1", "“hard update”", "Replace outright. Fast, and prone to oscillation."),
            ("target network", "“the frozen copy”", "The related standard trick: keep a separate copy of Q, used only for computing targets, updated slowly. Same purpose."),
        ])
        + key("""<p>Both refinements exist for the same reason: <b>the targets are computed from the network
being trained</b>. If the network lurches, every target lurches, and the network is chasing something that
keeps jumping. Slowing the network down slows the target down.</p>""")

        + h2("🕳", "Traps")
        + trap("""<p><b>τ too large.</b> Effectively a hard update — training oscillates, and the loss curve
looks like a heart-rate monitor.</p>""")
        + trap("""<p><b>τ too small.</b> The target barely moves, and learning is glacial. 0.001 to 0.01 is
the usual range.</p>""")

        + h2("✅", "Check yourself")
        + quiz([
            ("Why does DQN need soft updates when supervised learning does not?",
             "<p>Because in supervised learning the targets y are fixed data. In DQN they are computed "
             "from the network itself, so changing the network changes the targets. Soft updates keep "
             "the target from moving too fast.</p>"),
            ("τ = 1. What is happening?",
             "<p>A full replacement each step. The targets jump every iteration and training typically "
             "becomes unstable.</p>"),
            ("Is mini-batch specific to reinforcement learning?",
             "<p>No — it is standard for all deep learning. It appears here because the replay buffer "
             "makes the dataset large enough to force the issue.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("paper", "https://arxiv.org/abs/1509.02971",
             "Lillicrap et al. (2015) — Continuous control with deep RL (DDPG)",
             "Where the soft-update rule with τ comes from. Also extends DQN to continuous actions."),
            ("paper", "https://www.nature.com/articles/nature14236",
             "Mnih et al. (2015) — DQN",
             "Uses the hard-update target network variant: freeze a copy, refresh it every C steps."),
            ("lab", REPO + "/week3/C3W3A1/C3_W3_A1_Assignment.ipynb",
             "Week 3 assignment",
             "In this repo. Both refinements are in the training loop you complete."),
        ])
    )))

# ============================================================ 16
L.append(dict(
    slug="16-state-of-rl", title="The state of reinforcement learning", mins=8, tag="core",
    lede="An honest closing assessment — and the end of the specialization.",
    body=(
        pretest("""<p>RL produces spectacular demos. <b>Guess how much of deployed machine learning actually uses it</b>, and why.</p>""",
        """<p>Watch for the honest assessment: the gap between simulation and the physical world is the recurring obstacle.</p>""")
        + h2("🎈", "The idea, in plain words")
        + kid("""<p>Reinforcement learning is genuinely exciting, and it is also the most over-hyped part of
machine learning right now.</p>
<p>In a video game or a simulator, it is astonishing — it can beat the best humans in the world. In the
real world, on real robots, it is fragile, expensive, and much harder than the demos suggest.</p>
<p>Worth knowing. Not usually the first tool to reach for.</p>""")

        + h2("🎬", "Watch it move")
        + demo("rlstate", "The scorecard",
               "three things it does well, three that make it hard")

        + h2("⚖️", "The honest assessment")
        + grid2(
            card("<h3>What is real</h3><ul>"
                 "<li>Superhuman play in games with perfect simulators.</li>"
                 "<li>Genuine wins in control: data-centre cooling, some robotics.</li>"
                 "<li>RLHF — how essentially every modern chat model is tuned. Quietly the biggest "
                 "deployed application of RL that exists.</li></ul>"),
            card("<h3>What is hard</h3><ul>"
                 "<li>Simulation-to-reality transfer. The simulator is never the world.</li>"
                 "<li>Sample efficiency — millions of trials, which is fine in sim and impossible "
                 "with a real drone.</li>"
                 "<li>Extreme sensitivity to reward design and hyperparameters.</li>"
                 "<li>Far fewer production applications than supervised learning.</li></ul>"))
        + key("""<p>Andrew’s own framing, and it is worth copying: the ideas are important and the research
is exciting, and the number of <em>commercial</em> applications today is much smaller than the attention
suggests. Being able to say that clearly is a mark of understanding the field rather than its
marketing.</p>""")

        + h2("🎓", "You have finished the specialization")
        + """<p>Three courses. Here is what you can now do.</p>
<ul>
<li><b>Course 1</b> — linear and logistic regression, gradient descent, regularisation. The foundation
everything else is built on.</li>
<li><b>Course 2</b> — neural networks forwards and backwards, activation functions, softmax, Adam; then
the judgement half: bias/variance, error analysis, metrics; then decision trees and XGBoost.</li>
<li><b>Course 3</b> — clustering, anomaly detection, collaborative and content-based recommenders, PCA,
and reinforcement learning from the Bellman equation to a working deep Q-network.</li>
</ul>
<p>That is a genuinely broad foundation. What you do not yet have is depth in any one area, or experience
with the messy parts — data collection, deployment, monitoring — which no course can give you.</p>"""

        + h2("➡️", "Sensible next steps")
        + grid3(
            card("<h3>Build something</h3><p>Take a dataset you actually care about and go end to end. "
                 "The C2 W3 diagnostics are the part you will use every single day.</p>"),
            card("<h3>Go deeper</h3><p>The Deep Learning Specialization for neural networks; fast.ai for a "
                 "top-down practical route; Sutton &amp; Barto if RL is what caught you.</p>"),
            card("<h3>Read papers</h3><p>You can now read most applied ML papers. Start with the ones "
                 "linked throughout these notes — you have the vocabulary for all of them.</p>"))
        + note("""<p>The single most transferable thing in these three courses is not any algorithm. It is
Course 2, Week 3: split your data honestly, diagnose before you fix, look at your errors by hand, and
measure the thing you actually care about. That survives every change of framework and every new model
architecture.</p>""", "If you remember one thing")

        + h2("✅", "Check yourself")
        + quiz([
            ("Why does RL work so much better in simulation than on real robots?",
             "<p>It needs millions of trials. In simulation those are free and fast; on real hardware "
             "they are slow, expensive, and each failure may break something. And a policy trained in "
             "simulation often fails on the real system because the simulator was subtly wrong.</p>"),
            ("What is the most widely deployed application of RL today?",
             "<p><b>RLHF</b> — reinforcement learning from human feedback, used to align large language "
             "models. Not a robot in sight.</p>"),
        ])

        + h2("🔗", "Go deeper")
        + links([
            ("book", "http://incompleteideas.net/book/the-book-2nd.html",
             "Sutton & Barto — Reinforcement Learning: An Introduction",
             "Free, and the definitive text. If this week interested you, this is where to go next."),
            ("video", "https://www.youtube.com/playlist?list=PLqYmG7hTraZDVH599EItlEWsUOsJbAodm",
             "DeepMind × UCL — Reinforcement Learning Lecture Series",
             "A full graduate course, free. Considerably more rigorous than this week."),
            ("paper", "https://arxiv.org/abs/2203.02155",
             "Ouyang et al. (2022) — Training language models to follow instructions with human feedback",
             "The InstructGPT paper: RLHF, in detail. This is where the ideas in this week are actually deployed at scale."),
            ("docs", "https://www.deeplearning.ai/courses/deep-learning-specialization/",
             "The Deep Learning Specialization",
             "The natural next course if Course 2 was your favourite part."),
        ])
    )))

WEEK = dict(
    course="C3", week=3, title="Reinforcement Learning",
    time="~6–8 h with labs",
    goal="Go from the Mars rover and the Bellman equation to a working deep Q-network that lands a lunar "
         "lander — including why reward design is the hard part.",
    lessons=L,
)
